//! Device-address normalization and conservative identity evidence.

/// Canonicalizes a MAC address to lower-case colon-separated form.
pub fn canonical_mac(input: &str) -> Option<String> {
    let compact: String = input.chars().filter(|c| *c != ':' && *c != '-').collect();
    if compact.len() != 12 || !compact.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    Some(
        compact
            .as_bytes()
            .chunks(2)
            .map(|pair| std::str::from_utf8(pair).ok().map(str::to_ascii_lowercase))
            .collect::<Option<Vec<_>>>()?
            .join(":"),
    )
}

/// Returns true when a canonical MAC address has the locally administered bit set.
#[must_use]
pub fn is_locally_administered(mac: &str) -> Option<bool> {
    let canonical = canonical_mac(mac)?;
    let first = canonical.get(0..2)?;
    u8::from_str_radix(first, 16)
        .ok()
        .map(|octet| octet & 0x02 != 0)
}

/// Address persistence classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AddressKind {
    /// Universally administered address; potentially stable hardware identity.
    Public,
    /// Locally administered/randomized address; must not be treated as stable identity alone.
    Randomized,
}

/// Evidence usable for re-identification without claiming certainty.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct IdentityEvidence {
    /// Advertised device name when present.
    pub name: Option<String>,
    /// Manufacturer/company identifier when present.
    pub manufacturer_id: Option<u16>,
    /// Sorted service UUID labels represented as strings.
    pub services: Vec<String>,
    /// Stable payload fingerprint generated by a caller.
    pub payload_fingerprint: Option<String>,
}

/// Conservative device identity record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeviceIdentity {
    /// Current observed address.
    pub address: String,
    /// Address persistence classification.
    pub address_kind: AddressKind,
    /// Supplemental identity evidence.
    pub evidence: IdentityEvidence,
}

impl DeviceIdentity {
    /// Builds an identity from an observed MAC and evidence.
    pub fn new(address: &str, evidence: IdentityEvidence) -> Option<Self> {
        let address = canonical_mac(address)?;
        let address_kind = if is_locally_administered(&address)? {
            AddressKind::Randomized
        } else {
            AddressKind::Public
        };
        Some(Self {
            address,
            address_kind,
            evidence,
        })
    }
}
