//! Parity-frontier report previously generated by `tools/parity_report.py`.

/// Builds the parity coverage markdown from the ABI census and the compat registry source.
///
/// Symbol order matches the retired script: a sorted unique set of
/// `UNIFFI_META_BLERADAR_CORE_FUNC_*` suffixes, then a sorted unique set of
/// `METHOD` and `CONSTRUCTOR` suffixes. Registered contract names stay in
/// source order.
#[must_use]
pub fn coverage_markdown(abi_text: &str, compat_source: &str) -> String {
    let mut observed = unique_suffixes(abi_text, &["UNIFFI_META_BLERADAR_CORE_FUNC_"]);
    observed.extend(unique_suffixes(
        abi_text,
        &[
            "UNIFFI_META_BLERADAR_CORE_METHOD_",
            "UNIFFI_META_BLERADAR_CORE_CONSTRUCTOR_",
        ],
    ));
    let registered = registered_names(compat_source);
    let remaining = observed.len().saturating_sub(registered.len());

    let mut lines = vec![
        "# Parity Coverage".to_string(),
        String::new(),
        "Generated from `docs/NATIVE_ABI.txt` and the semantic compatibility registry.".to_string(),
        String::new(),
        format!(
            "- Observed UniFFI function/method/constructor symbols: **{}**",
            observed.len()
        ),
        format!(
            "- Contracts with explicit semantic migration status: **{}**",
            registered.len()
        ),
        format!(
            "- Remaining observed symbols requiring semantic registration/characterization: **{remaining}**"
        ),
        String::new(),
        "## Registered semantic frontier".to_string(),
        String::new(),
    ];
    for name in &registered {
        lines.push(format!("- `{name}`"));
    }
    lines.push(String::new());
    lines.push("## Interpretation".to_string());
    lines.push(String::new());
    lines.push(
        "A symbol appearing in the APK is not automatically considered migrated. Exact parity requires characterization of inputs, outputs, side effects, and errors against the immutable oracle. The registry intentionally records that distinction."
            .to_string(),
    );
    lines.push(String::new());
    lines.join("\n")
}

/// Sorted, unique captures of `[A-Z0-9_]+` immediately after any of `prefixes`.
fn unique_suffixes(text: &str, prefixes: &[&str]) -> Vec<String> {
    let bytes = text.as_bytes();
    let mut found = Vec::new();
    let mut index = 0;
    while index < bytes.len() {
        let mut matched = false;
        for prefix in prefixes {
            let prefix_bytes = prefix.as_bytes();
            if index + prefix_bytes.len() <= bytes.len()
                && &bytes[index..index + prefix_bytes.len()] == prefix_bytes
            {
                let start = index + prefix_bytes.len();
                let mut end = start;
                while end < bytes.len() && is_symbol_byte(bytes[end]) {
                    end += 1;
                }
                if end > start
                    && let Ok(name) = std::str::from_utf8(&bytes[start..end])
                {
                    found.push(name.to_string());
                }
                index = end.max(index + 1);
                matched = true;
                break;
            }
        }
        if !matched {
            index += 1;
        }
    }
    found.sort();
    found.dedup();
    found
}

fn is_symbol_byte(byte: u8) -> bool {
    byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_'
}

/// `name: "..."` strings in source order, including duplicates, as `re.findall` did.
fn registered_names(compat_source: &str) -> Vec<String> {
    const KEY: &str = "name: \"";
    let mut names = Vec::new();
    let mut rest = compat_source;
    while let Some(offset) = rest.find(KEY) {
        let after = &rest[offset + KEY.len()..];
        let Some(end) = after.find('"') else {
            break;
        };
        names.push(after[..end].to_string());
        rest = &after[end + 1..];
    }
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn report_matches_the_retired_script_shape() {
        let abi = "\
UNIFFI_META_BLERADAR_CORE_FUNC_HAVERSINE_M
UNIFFI_META_BLERADAR_CORE_METHOD_LOCK
UNIFFI_META_BLERADAR_CORE_FUNC_HAVERSINE_M
UNIFFI_META_BLERADAR_CORE_CONSTRUCTOR_TRACKER
";
        let compat = "name: \"haversine_m\"\nname: \"lock\"\n";
        let report = coverage_markdown(abi, compat);
        assert!(report.contains("**3**"));
        assert!(report.contains("**2**"));
        assert!(report.contains("**1**"));
        assert!(report.contains("- `haversine_m`\n- `lock`"));
    }
}
