//! Executed-oracle differential *coverage* for the pure geodesy contracts
//! `haversine_m` and `bearing_deg` (`docs/ORACLE_DIFFERENTIAL.md`,
//! `docs/AUTONOMOUS_DECISIONS.md` decision 73).
//!
//! `oracle_characterization.rs` locked `haversine_m` against the oracle at a
//! single coordinate pair and left `bearing_deg` with only "sampled outputs;
//! exhaustive differential parity is pending". `cargo xtask oracle-differential`
//! now executes the immutable oracle under `qemu-aarch64` against a real Bionic
//! runtime over 308 coordinate pairs (edge cases + a fixed-seed sweep) and
//! records each result in `oracle/geodesy_executed_vectors.tsv`. This test
//! replays that executed-oracle ground truth against the safe-Rust
//! reconstruction.
//!
//! Unlike the WiFi contracts (`oracle_differential.rs`, bit-exact), these are
//! transcendental: the oracle computes `sin`/`cos`/`asin`/`atan2` with Bionic
//! `libm` and the reconstruction with the host `libm`, which are not bit-identical.
//! The reconstruction therefore reproduces the executed oracle to a tiny
//! *physical* tolerance -- metres for distance, degrees for bearing -- not
//! bit-for-bit, so both contracts remain `SourceAnalog`; this is broad
//! executed-oracle differential COVERAGE (it would catch a changed Earth-radius
//! constant or a reworked formula), not a bit-exact promotion. The bound is far
//! tighter than any real formula/constant change (metres, degrees) yet loose
//! enough to absorb last-bit `libm` divergence (observed maxima: haversine a few
//! nanometres, bearing a few picodegrees, the latter amplified only at
//! ill-conditioned near-antipodal pairs).

use bleradar_compat::{ParityStatus, parity_status};
use bleradar_core::{LatLon, bearing_deg, haversine_m};

/// Executed-oracle ground truth, generated by `cargo xtask oracle-differential`.
const VECTORS: &str = include_str!("oracle/geodesy_executed_vectors.tsv");

/// The exact immutable oracle these vectors were read from.
const ORACLE_SO_SHA256: &str = "d14022cd113332312fb1719aafa107155a4c046c056cb9b2bcd3c94eb980b12d";

/// The reconstruction reproduces the executed oracle's distance to well under a
/// micrometre; a changed Earth radius or haversine formula moves it by metres.
const HAVERSINE_TOLERANCE_M: f64 = 1.0e-6;
/// The reconstruction reproduces the executed oracle's bearing to well under a
/// nanodegree (circular); a reworked bearing formula moves it by degrees.
const BEARING_TOLERANCE_DEG: f64 = 1.0e-8;

fn bits(field: &str) -> u64 {
    u64::from_str_radix(field, 16)
        .unwrap_or_else(|_| panic!("expected 16-hex-digit f64, got {field:?}"))
}

/// Smallest absolute angular difference on the [0, 360) circle.
fn circular_diff_deg(a: f64, b: f64) -> f64 {
    let raw = (a - b).abs() % 360.0;
    raw.min(360.0 - raw)
}

#[test]
fn reconstruction_matches_the_executed_oracle_geodesy_within_physical_tolerance() {
    let mut pairs = 0usize;
    let mut haversine_bit_exact = 0usize;
    let mut bearing_bit_exact = 0usize;
    let mut max_haversine_m = 0.0f64;
    let mut max_bearing_deg = 0.0f64;

    for (index, raw) in VECTORS.lines().enumerate() {
        let line = raw.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let lineno = index + 1;
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(
            f.len(),
            9,
            "line {lineno}: expected 9 columns, got {}",
            f.len()
        );
        assert_eq!(f[0], "GEO", "line {lineno}: unexpected tag {:?}", f[0]);
        assert_eq!(f[5], "0", "line {lineno}: oracle haversine status not ok");
        assert_eq!(f[7], "0", "line {lineno}: oracle bearing status not ok");

        let lat1 = f64::from_bits(bits(f[1]));
        let lon1 = f64::from_bits(bits(f[2]));
        let lat2 = f64::from_bits(bits(f[3]));
        let lon2 = f64::from_bits(bits(f[4]));
        let oracle_haversine = f64::from_bits(bits(f[6]));
        let oracle_bearing = f64::from_bits(bits(f[8]));

        let (a, b) = (
            LatLon::new(lat1, lon1).unwrap_or_else(|_| {
                panic!("line {lineno}: oracle input ({lat1},{lon1}) rejected by LatLon")
            }),
            LatLon::new(lat2, lon2).unwrap_or_else(|_| {
                panic!("line {lineno}: oracle input ({lat2},{lon2}) rejected by LatLon")
            }),
        );
        pairs += 1;

        let source_haversine = haversine_m(a, b);
        let source_bearing = bearing_deg(a, b);

        if source_haversine.to_bits() == oracle_haversine.to_bits() {
            haversine_bit_exact += 1;
        }
        if source_bearing.to_bits() == oracle_bearing.to_bits() {
            bearing_bit_exact += 1;
        }

        let dh = (source_haversine - oracle_haversine).abs();
        let db = circular_diff_deg(source_bearing, oracle_bearing);
        max_haversine_m = max_haversine_m.max(dh);
        max_bearing_deg = max_bearing_deg.max(db);

        assert!(
            dh <= HAVERSINE_TOLERANCE_M,
            "line {lineno}: haversine_m({lat1},{lon1},{lat2},{lon2}) source {source_haversine} vs executed oracle {oracle_haversine} differ by {dh} m (> {HAVERSINE_TOLERANCE_M})"
        );
        assert!(
            db <= BEARING_TOLERANCE_DEG,
            "line {lineno}: bearing_deg({lat1},{lon1},{lat2},{lon2}) source {source_bearing} vs executed oracle {oracle_bearing} differ by {db} deg (> {BEARING_TOLERANCE_DEG})"
        );
    }

    println!(
        "geodesy differential: {pairs} pairs; haversine max {max_haversine_m:e} m ({haversine_bit_exact} bit-exact); bearing max {max_bearing_deg:e} deg ({bearing_bit_exact} bit-exact)"
    );
    assert!(pairs >= 300, "too few coordinate pairs: {pairs}");
    // A meaningful differential over transcendentals is nearly all bit-exact and
    // never off by more than last-bit libm rounding; a formula/constant change
    // would blow past the physical tolerances above on many pairs.
    assert!(
        haversine_bit_exact * 2 >= pairs,
        "haversine unexpectedly non-bit-exact on most pairs: {haversine_bit_exact}/{pairs}"
    );
}

#[test]
fn geodesy_contracts_stay_source_analog_pending_bit_exact_parity() {
    // Transcendental libm divergence keeps these from bit-exact DifferentiallyVerified.
    for name in ["haversine_m", "bearing_deg"] {
        assert_eq!(
            parity_status(name),
            Some(ParityStatus::SourceAnalog),
            "{name} is executed-oracle differential COVERAGE, not a bit-exact promotion"
        );
    }
}

#[test]
fn executed_geodesy_vectors_are_pinned_to_the_immutable_oracle() {
    assert!(
        VECTORS.contains(ORACLE_SO_SHA256),
        "the committed geodesy vectors must record the immutable oracle .so SHA-256"
    );
    assert!(VECTORS.contains("qemu-aarch64"));
}
