//! Executed-oracle differential verification of the WiFi channel<->frequency
//! contracts (`docs/ORACLE_DIFFERENTIAL.md`, `docs/AUTONOMOUS_DECISIONS.md`
//! decision 72).
//!
//! Until now the WiFi contracts were `SourceAnalog`: the safe-Rust
//! reconstruction was compared only against a *hand-reconstructed* model of the
//! oracle (`oracle_characterization.rs::oracle_wifi_*`), never against the
//! oracle itself, because the immutable v0.3.0 native core is an aarch64
//! Android library and the sandbox has no device or emulator
//! (`docs/ISSUE_LEDGER.md` MIG-001/002/003).
//!
//! `cargo xtask oracle-differential` now executes that immutable library
//! directly -- under `qemu-aarch64` against a real Android Bionic runtime --
//! over a comprehensive input sweep and records each UniFFI result in
//! `oracle/wifi_executed_vectors.tsv`. This test replays that executed-oracle
//! ground truth and asserts:
//!
//! 1. the safe-Rust reconstruction reproduces every executed-oracle output
//!    across its `u16` input domain, and
//! 2. the oracle's wider `i32`/`Option<i32>` input domain collapses to `None`
//!    exactly where the reconstruction's `u16` contract cannot represent the
//!    input (the one documented, intentional divergence).
//!
//! This is real differential parity against the oracle binary, not against a
//! model of it, so `wifi_channel_to_frequency` and `wifi_frequency_to_channel`
//! are `DifferentiallyVerified`. The comparison reads baked vectors and needs
//! no emulator, so it runs in ordinary CI; `cargo xtask oracle-differential`
//! regenerates the vectors from the oracle and fails on any drift.

use bleradar_compat::{ParityStatus, parity_status};
use bleradar_core::{wifi_channel_to_frequency, wifi_frequency_to_channel};

/// Executed-oracle ground truth, generated by `cargo xtask oracle-differential`.
const VECTORS: &str = include_str!("oracle/wifi_executed_vectors.tsv");

/// The exact immutable oracle these vectors were read from; pinned so a silent
/// regeneration from a different binary is visible in review.
const ORACLE_SO_SHA256: &str = "d14022cd113332312fb1719aafa107155a4c046c056cb9b2bcd3c94eb980b12d";

/// Parses a UniFFI `Option<i32>` field: the literal `None` or a decimal `i32`.
fn parse_opt(field: &str) -> Option<i32> {
    if field == "None" {
        None
    } else {
        Some(
            field
                .parse::<i32>()
                .unwrap_or_else(|_| panic!("expected `None` or an i32, got {field:?}")),
        )
    }
}

#[derive(Default)]
struct Coverage {
    wcf_rows: usize,
    wfc_rows: usize,
    source_compared: usize,
    source_some: usize,
    domain_divergence: usize,
}

#[test]
fn reconstruction_reproduces_the_executed_oracle_over_its_domain() {
    let mut cov = Coverage::default();

    for (index, raw) in VECTORS.lines().enumerate() {
        let line = raw.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let lineno = index + 1;
        let mut fields = line.split('\t');
        let contract = fields.next().expect("non-empty line has a first field");
        let input = fields
            .next()
            .unwrap_or_else(|| panic!("line {lineno}: missing input column"));
        let output = fields
            .next()
            .unwrap_or_else(|| panic!("line {lineno}: missing output column"));
        assert!(
            fields.next().is_none(),
            "line {lineno}: unexpected extra columns"
        );
        let oracle = parse_opt(output);

        match contract {
            "WCF" => {
                cov.wcf_rows += 1;
                let channel: i32 = input
                    .parse()
                    .unwrap_or_else(|_| panic!("line {lineno}: WCF input {input:?} is not i32"));
                match u16::try_from(channel) {
                    Ok(channel_u16) => {
                        let source = wifi_channel_to_frequency(channel_u16).map(i32::from);
                        assert_eq!(
                            source, oracle,
                            "wifi_channel_to_frequency({channel}): source {source:?} != executed oracle {oracle:?}"
                        );
                        cov.source_compared += 1;
                        cov.source_some += usize::from(oracle.is_some());
                    }
                    Err(_) => {
                        assert_eq!(
                            oracle, None,
                            "wifi_channel_to_frequency({channel}) is outside the source's u16 domain; the executed oracle must return None there"
                        );
                        cov.domain_divergence += 1;
                    }
                }
            }
            "WFC" => {
                cov.wfc_rows += 1;
                match parse_opt(input) {
                    Some(mhz) => match u16::try_from(mhz) {
                        Ok(mhz_u16) => {
                            let source = wifi_frequency_to_channel(mhz_u16).map(i32::from);
                            assert_eq!(
                                source, oracle,
                                "wifi_frequency_to_channel({mhz}): source {source:?} != executed oracle {oracle:?}"
                            );
                            cov.source_compared += 1;
                            cov.source_some += usize::from(oracle.is_some());
                        }
                        Err(_) => {
                            assert_eq!(
                                oracle, None,
                                "wifi_frequency_to_channel({mhz}) is outside the source's u16 domain; the executed oracle must return None there"
                            );
                            cov.domain_divergence += 1;
                        }
                    },
                    None => {
                        assert_eq!(
                            oracle, None,
                            "the executed oracle maps a None frequency to None; the source's u16 contract cannot express None"
                        );
                        cov.domain_divergence += 1;
                    }
                }
            }
            other => panic!("line {lineno}: unknown contract tag {other:?}"),
        }
    }

    // The differential must be substantial and exercise real Some(..) outputs,
    // not a degenerate all-None stub.
    assert!(cov.wcf_rows >= 200, "too few WCF vectors: {}", cov.wcf_rows);
    assert!(cov.wfc_rows >= 200, "too few WFC vectors: {}", cov.wfc_rows);
    assert!(
        cov.source_compared >= 300,
        "too few in-domain source comparisons: {}",
        cov.source_compared
    );
    assert!(
        cov.source_some >= 100,
        "too few Some(..) outputs exercised: {}",
        cov.source_some
    );
    assert!(
        cov.domain_divergence >= 5,
        "the i32-vs-u16 domain-divergence rows are missing: {}",
        cov.domain_divergence
    );
}

#[test]
fn wifi_contracts_are_differentially_verified_against_the_executed_oracle() {
    for name in ["wifi_channel_to_frequency", "wifi_frequency_to_channel"] {
        assert_eq!(
            parity_status(name),
            Some(ParityStatus::DifferentiallyVerified),
            "{name} must be DifferentiallyVerified once the executed-oracle differential passes"
        );
    }
}

#[test]
fn executed_vector_provenance_is_pinned_to_the_immutable_oracle() {
    assert!(
        VECTORS.contains(ORACLE_SO_SHA256),
        "the committed vectors must record the immutable oracle .so SHA-256"
    );
    assert!(
        VECTORS.contains("qemu-aarch64"),
        "the committed vectors must record the executed-oracle provenance"
    );
}
