//! `cargo xtask verify-api-live`: runs the app's real `ApiHttpServer` on the
//! host JVM — the exact Java class the APK ships, with fixture sources in
//! place of the Bluetooth engine — and proves it end to end:
//!
//! 1. every HTTP contract by real requests over loopback (status codes,
//!    headers, the dashboard bytes, `404`/`405`/`400`), with the three JSON
//!    documents compared byte for byte with the fixtures the browser proofs
//!    use (`dashboard::DEVICES_JSON` and friends), so the mock in
//!    `verify-dashboard-live` is proven to be what the Java writer emits;
//!    scan control (`POST /api/scan/start|stop`) against a scripted
//!    `ScanControl` — a pause reflected by every document, an accepted
//!    start, each documented refusal as `409`, a control that throws
//!    answered `500` with the server still up, a request body consumed, a
//!    body declared beyond the cap refused with `413`;
//! 2. the committed dashboard rendered by headless Chromium *from that
//!    server*, checked with the same healthy-scenario DOM markers.
//!
//! The server links the host `bleradar-jni` library so `native_available`
//! is the real answer. Needs a JDK (`javac`/`java`) and a Chromium/Chrome
//! binary; CI runs it in the `gates` job.

use std::fs;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::TcpStream;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, Instant};

use crate::dashboard::{
    self, DASHBOARD_ASSET_PATH, DEVICES_JSON, METHOD_NOT_ALLOWED_JSON, NOT_FOUND_JSON,
    SCAN_STARTED_JSON, SCAN_STOPPED_JSON, STATUS_JSON, Scenario, UPDATES_JSON,
};

/// The Java sources the server needs on a plain JVM: none of them may
/// reference `android.*` (the compile below has no `android.jar`).
pub(crate) const HOST_JAVA_SOURCES: &[&str] = &[
    "ApiHttpServer.java",
    "AssetSource.java",
    "Blip.java",
    "Json.java",
    "NativeRadar.java",
    "ReleaseManifest.java",
    "ReleaseManifestSource.java",
    "ScanControl.java",
    "SnapshotSource.java",
    "Streams.java",
    "UpdateStatusSource.java",
];

/// `/api/status` while the scripted control has paused the scan: no uptime.
const PAUSED_STATUS_JSON: &str =
    r#"{"scanning":false,"device_count":4,"native_available":true,"uptime_ms":0}"#;

/// The four refusals `ApiHttpServer.startRefusalLabel` documents, as the
/// harness script answers them in turn (label, exact `409` body).
const START_REFUSALS: [(&str, &str); 4] = [
    (
        "permissions missing",
        r#"{"error":"Bluetooth permissions not granted; open the app once to grant them"}"#,
    ),
    ("Bluetooth off", r#"{"error":"Bluetooth is off"}"#),
    (
        "scanner unavailable",
        r#"{"error":"Bluetooth LE scanner unavailable"}"#,
    ),
    (
        "background start refused",
        r#"{"error":"Android refused a background start; open the app once"}"#,
    ),
];

/// The `500` a control that throws must produce (the exception's class).
const CONTROL_THREW_JSON: &str = r#"{"error":"Internal error: IllegalStateException"}"#;

pub(crate) const JAVA_PACKAGE_DIR: &str = "android/app/src/main/java/com/hse/bleradar";
/// How long the JVM may take to print its bound port.
const STARTUP_TIMEOUT: Duration = Duration::from_secs(60);
/// How long one request may take end to end.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(10);
/// How long a reset may take to follow a graceful end of stream.
const RESET_GRACE: Duration = Duration::from_millis(300);

/// The host harness: fixture sources equal to the browser fixtures, a
/// scripted scan control, an ephemeral port, and a run that lasts until
/// stdin closes.
pub fn api_smoke_java_source() -> String {
    r#"package com.hse.bleradar;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/** Runs the real ApiHttpServer with fixture sources; generated by xtask. */
public final class ApiSmoke {

    private static final long NOW_UPTIME_MS = 100_000L;
    private static final long NOW_EPOCH_MS = 1_757_700_000_000L;
    private static final long SCAN_UPTIME_MS = 3_723_000L;

    /** The scripted scan state; starts scanning, as the browser fixtures say. */
    private static volatile boolean scanning = true;
    /** How many starts the scripted control has answered. */
    private static int starts;

    public static void main(String[] args) throws Exception {
        final Path dashboard = Paths.get(args[0]);
        NativeRadar.ensureLoaded();
        if (!NativeRadar.isAvailable()) {
            throw new IllegalStateException("native library not available: " + NativeRadar.loadError());
        }
        final List<Blip> devices = new ArrayList<>();
        devices.add(blip("AA:BB:CC:DD:EE:01", "Tag Alpha", 1.234, 0.8, 1.9, -61.4,
                NativeRadar.PROXIMITY_NEAR, NativeRadar.TREND_STRONGER, NativeRadar.FRESHNESS_LIVE, 87, 420));
        devices.add(blip("AA:BB:CC:DD:EE:02", "<b>evil</b> \"Ünïcødé\" \\ 😀", 7.5, 5.2, 11.0, -78.0,
                NativeRadar.PROXIMITY_MID, NativeRadar.TREND_WEAKER, NativeRadar.FRESHNESS_RECENT, 52, 12345));
        devices.add(blip("AA:BB:CC:DD:EE:03", null, Double.NaN, Double.NaN, Double.NaN, -90.2,
                NativeRadar.PROXIMITY_FAR, -1, NativeRadar.FRESHNESS_STALE, 0, 75000));
        devices.add(blip("AA:BB:CC:DD:EE:04", "Beacon Delta", 0.4, 0.3, 0.6, -45.0,
                NativeRadar.PROXIMITY_IMMEDIATE, NativeRadar.TREND_STABLE, NativeRadar.FRESHNESS_LIVE, 99, 90));

        SnapshotSource source = new SnapshotSource() {
            @Override
            public List<Blip> snapshot() {
                return new ArrayList<>(devices);
            }

            @Override
            public boolean isScanning() {
                return scanning;
            }

            @Override
            public long getUptimeMillis() {
                return scanning ? SCAN_UPTIME_MS : 0L;
            }
        };
        // The script: the first start is accepted, the next four answer each
        // documented refusal in turn, the sixth throws (the server must answer
        // 500 and stay up), every later one is accepted; a stop always pauses.
        ScanControl control = new ScanControl() {
            @Override
            public synchronized int requestStart() {
                starts++;
                switch (starts) {
                    case 2:
                        return START_PERMISSIONS_MISSING;
                    case 3:
                        return START_BLUETOOTH_OFF;
                    case 4:
                        return START_UNAVAILABLE;
                    case 5:
                        return START_BACKGROUND_RESTRICTED;
                    case 6:
                        throw new IllegalStateException("scripted failure");
                    default:
                        scanning = true;
                        return START_ACCEPTED;
                }
            }

            @Override
            public void requestStop() {
                scanning = false;
            }
        };
        UpdateStatusSource updates = new UpdateStatusSource() {
            @Override
            public long getLastCheckTimeMs() {
                return 1_757_600_000_000L;
            }

            @Override
            public long getNextCheckTimeMs() {
                return 1_757_686_400_000L;
            }

            @Override
            public int getRetryCount() {
                return 2;
            }
        };
        AssetSource assets = name -> {
            if (!ApiHttpServer.DASHBOARD_ASSET.equals(name)) {
                throw new IOException("unexpected asset " + name);
            }
            return Files.newInputStream(dashboard);
        };
        ApiHttpServer server = new ApiHttpServer(
                source, updates, assets, () -> NOW_UPTIME_MS, () -> NOW_EPOCH_MS, control, 0);
        server.start();
        int port = server.boundPort();
        if (port <= 0) {
            throw new IllegalStateException("server did not bind");
        }
        System.out.println("port=" + port);
        System.out.flush();
        // Serve until xtask closes stdin.
        InputStream in = System.in;
        while (in.read() != -1) {
            // waiting
        }
        server.stop();
    }

    private static Blip blip(String address, String name, double distance, double lower, double upper,
            double rssi, int proximity, int trend, int freshness, int confidence, long agoMs) {
        Blip blip = new Blip(address);
        blip.name = name;
        blip.distanceMetres = distance;
        blip.distanceLowerBoundMetres = lower;
        blip.distanceUpperBoundMetres = upper;
        blip.lastRssiDbm = rssi;
        blip.proximity = proximity;
        blip.trend = trend;
        blip.freshness = freshness;
        blip.confidencePercent = confidence;
        blip.lastSeenUptimeMillis = NOW_UPTIME_MS - agoMs;
        return blip;
    }
}
"#
    .to_string()
}

/// One parsed HTTP response.
#[derive(Debug)]
pub struct HttpResponse {
    /// The status code from the status line.
    pub status: u16,
    /// Header names and values, in order.
    pub headers: Vec<(String, String)>,
    /// The body bytes.
    pub body: Vec<u8>,
}

impl HttpResponse {
    /// The first header with `name` (case-insensitive).
    pub fn header(&self, name: &str) -> Option<&str> {
        self.headers
            .iter()
            .find(|(key, _)| key.eq_ignore_ascii_case(name))
            .map(|(_, value)| value.as_str())
    }
}

/// `text` as a Java string literal: quotes, backslashes and line breaks escaped.
pub fn java_string_literal(text: &str) -> String {
    let mut literal = String::from("\"");
    for c in text.chars() {
        match c {
            '\\' => literal.push_str("\\\\"),
            '"' => literal.push_str("\\\""),
            '\n' => literal.push_str("\\n"),
            '\r' => literal.push_str("\\r"),
            '\t' => literal.push_str("\\t"),
            c => literal.push(c),
        }
    }
    literal.push('"');
    literal
}

/// The manifest-source harness: the real `ReleaseManifestSource` against a
/// scripted local server (a valid manifest — `ok_manifest`, the one
/// `release-manifest` would publish for the committed APK, so the real core's
/// acceptance of it is proven every run — no release, a server fault, a
/// redirect the client cannot follow, an oversized body, a body the Rust core
/// rejects, a stalled answer, a refused connection, a malformed URL), each
/// fetch's outcome run through the real `remoteManifestDisposition` export
/// and printed as one line.
pub fn manifest_source_smoke_java_source(ok_manifest: &str) -> String {
    let source = r#"package com.hse.bleradar;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;

/** Fetches release manifests from a scripted local server; generated by xtask. */
public final class ManifestSourceSmoke {

    private static final String MANIFEST = __OK_MANIFEST__;
    private static final int MAX_BYTES = 16 * 1024;
    private static final int TIMEOUT_MS = 10_000;
    private static final int SHORT_TIMEOUT_MS = 1_000;

    public static void main(String[] args) throws Exception {
        NativeRadar.ensureLoaded();
        if (!NativeRadar.isAvailable()) {
            throw new IllegalStateException("native library not available: " + NativeRadar.loadError());
        }
        HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/ok", answer(200, MANIFEST));
        server.createContext("/missing", answer(404, "no release"));
        server.createContext("/down", answer(503, "later"));
        // A redirect the client cannot follow (no Location header) is left
        // as the 3xx it is: an answer, and one without a release.
        server.createContext("/redirect", answer(301, "moved"));
        StringBuilder large = new StringBuilder();
        for (int i = 0; i <= MAX_BYTES; i++) {
            large.append('x');
        }
        server.createContext("/large", answer(200, large.toString()));
        server.createContext("/junk", answer(200, "not = a manifest\n"));
        server.createContext("/slow", exchange -> {
            try {
                Thread.sleep(SHORT_TIMEOUT_MS * 3);
            } catch (InterruptedException ignored) {
                // the client has given up by then
            }
            respond(exchange, 200, MANIFEST);
        });
        server.start();
        int port = server.getAddress().getPort();
        int closedPort;
        try (ServerSocket probe = new ServerSocket(0)) {
            closedPort = probe.getLocalPort();
        }
        String base = "http://127.0.0.1:" + port;
        try {
            report("ok", fetch(base + "/ok", TIMEOUT_MS));
            report("missing", fetch(base + "/missing", TIMEOUT_MS));
            report("down", fetch(base + "/down", TIMEOUT_MS));
            report("redirect", fetch(base + "/redirect", TIMEOUT_MS));
            report("large", fetch(base + "/large", TIMEOUT_MS));
            report("junk", fetch(base + "/junk", TIMEOUT_MS));
            report("slow", fetch(base + "/slow", SHORT_TIMEOUT_MS));
            report("refused", fetch("http://127.0.0.1:" + closedPort + "/ok", TIMEOUT_MS));
            report("malformed", fetch("not a url", TIMEOUT_MS));
        } finally {
            server.stop(0);
        }
    }

    private static ReleaseManifestSource.Fetch fetch(String url, int timeoutMs) {
        return ReleaseManifestSource.fetch(url, timeoutMs, timeoutMs, MAX_BYTES);
    }

    /** Exactly what UpdateCheckService does with a fetch, then the real disposition. */
    private static void report(String scenario, ReleaseManifestSource.Fetch fetch) {
        int failure = fetch.failureKind;
        boolean accepted = false;
        if (failure == NativeRadar.MANIFEST_FETCH_ANSWERED && fetch.text != null) {
            accepted = NativeRadar.releaseManifestCanonical(fetch.text) != null;
            if (!accepted) {
                failure = NativeRadar.MANIFEST_FETCH_REJECTED;
            }
        }
        int disposition = NativeRadar.remoteManifestDisposition(fetch.httpStatus, failure);
        System.out.println("scenario=" + scenario + " status=" + fetch.httpStatus + " failure=" + failure
                + " accepted=" + accepted + " disposition=" + disposition + " detail=" + fetch.detail);
    }

    private static HttpHandler answer(int status, String body) {
        return exchange -> respond(exchange, status, body);
    }

    private static void respond(HttpExchange exchange, int status, String body) throws IOException {
        byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
        exchange.getResponseHeaders().set("Content-Type", "text/plain; charset=utf-8");
        exchange.sendResponseHeaders(status, bytes.length);
        try (OutputStream out = exchange.getResponseBody()) {
            out.write(bytes);
        }
        exchange.close();
    }
}
"#;
    source.replace("__OK_MANIFEST__", &java_string_literal(ok_manifest))
}

/// What each manifest-source scenario must report: `(status, failure kind,
/// accepted, disposition)` — the fetcher's classification and the Rust
/// disposition of it. `0` status with kind `1` is a transport failure.
const MANIFEST_SOURCE_EXPECTATIONS: [(&str, u16, u8, bool, u8); 9] = [
    ("ok", 200, 0, true, 0),
    ("missing", 404, 0, false, 2),
    ("down", 503, 0, false, 1),
    ("redirect", 301, 0, false, 2),
    ("large", 200, 2, false, 2),
    ("junk", 200, 3, false, 2),
    ("slow", 0, 1, false, 1),
    ("refused", 0, 1, false, 1),
    ("malformed", 0, 1, false, 1),
];

/// Checks the harness's report lines against [`MANIFEST_SOURCE_EXPECTATIONS`]:
/// every scenario exactly once, each field as expected.
pub fn check_manifest_source_report(output: &str) -> Result<usize, String> {
    let mut seen = Vec::new();
    for line in output.lines().filter(|line| line.starts_with("scenario=")) {
        let mut fields = std::collections::BTreeMap::new();
        for token in line.split_whitespace() {
            if let Some((key, value)) = token.split_once('=') {
                // `detail=` runs to the end of the line and may contain spaces;
                // only the first five keys are structured.
                if key == "detail" {
                    break;
                }
                fields.insert(key, value);
            }
        }
        let scenario = fields.get("scenario").copied().unwrap_or_default();
        let expected = MANIFEST_SOURCE_EXPECTATIONS
            .iter()
            .find(|(name, ..)| *name == scenario)
            .ok_or_else(|| format!("unexpected scenario line: {line}"))?;
        let reported = (
            fields.get("status").copied().unwrap_or_default(),
            fields.get("failure").copied().unwrap_or_default(),
            fields.get("accepted").copied().unwrap_or_default(),
            fields.get("disposition").copied().unwrap_or_default(),
        );
        let wanted = (
            expected.1.to_string(),
            expected.2.to_string(),
            expected.3.to_string(),
            expected.4.to_string(),
        );
        if reported
            != (
                wanted.0.as_str(),
                wanted.1.as_str(),
                wanted.2.as_str(),
                wanted.3.as_str(),
            )
        {
            return Err(format!(
                "scenario {scenario}: expected status={} failure={} accepted={} disposition={}; got {line}",
                wanted.0, wanted.1, wanted.2, wanted.3
            ));
        }
        if seen.contains(&scenario) {
            return Err(format!("scenario {scenario} reported twice"));
        }
        seen.push(scenario);
    }
    let missing: Vec<&str> = MANIFEST_SOURCE_EXPECTATIONS
        .iter()
        .map(|(name, ..)| *name)
        .filter(|name| !seen.contains(name))
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "scenarios not reported: {}; output:\n{output}",
            missing.join(", ")
        ));
    }
    Ok(seen.len())
}

/// Parses a complete `HTTP/1.1` response (the server closes the connection
/// after every response, so the whole stream is one response).
pub fn parse_http_response(raw: &[u8]) -> Result<HttpResponse, String> {
    let split = raw
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .ok_or("response has no header terminator")?;
    let head = String::from_utf8_lossy(&raw[..split]);
    let body = raw[split + 4..].to_vec();
    let mut lines = head.split("\r\n");
    let status_line = lines.next().ok_or("empty response")?;
    let status = status_line
        .strip_prefix("HTTP/1.1 ")
        .and_then(|rest| rest.split(' ').next())
        .and_then(|code| code.parse::<u16>().ok())
        .ok_or_else(|| format!("malformed status line {status_line:?}"))?;
    let headers = lines
        .filter_map(|line| {
            let (name, value) = line.split_once(':')?;
            Some((name.trim().to_string(), value.trim().to_string()))
        })
        .collect();
    Ok(HttpResponse {
        status,
        headers,
        body,
    })
}

/// Sends `request` (raw bytes, request line included) to the loopback
/// `port` and returns the parsed response.
pub fn http_request(port: u16, request: &[u8]) -> Result<HttpResponse, String> {
    let (_, raw) = exchange(port, request)?;
    parse_http_response(&raw)
}

/// Like [`http_request`], and additionally requires the server to have
/// closed the connection without resetting it. A server that closes with
/// the request body unread resets the connection; the JDK shuts the socket
/// down before closing it, so `read_to_end` still sees a clean end of
/// stream and the reset shows only as the socket's pending error, moments
/// after the answer.
pub fn http_request_clean_close(port: u16, request: &[u8]) -> Result<HttpResponse, String> {
    let (stream, raw) = exchange(port, request)?;
    let deadline = Instant::now() + RESET_GRACE;
    loop {
        if let Some(error) = stream
            .take_error()
            .map_err(|e| format!("reading the socket error: {e}"))?
        {
            return Err(format!(
                "the server reset the connection after answering ({error}): the request body was left unread"
            ));
        }
        if Instant::now() >= deadline {
            return parse_http_response(&raw);
        }
        thread::sleep(Duration::from_millis(10));
    }
}

/// One connection: sends `request` and reads to the end of the stream.
fn exchange(port: u16, request: &[u8]) -> Result<(TcpStream, Vec<u8>), String> {
    let mut stream = TcpStream::connect(("127.0.0.1", port))
        .map_err(|e| format!("connecting to 127.0.0.1:{port}: {e}"))?;
    stream
        .set_read_timeout(Some(REQUEST_TIMEOUT))
        .map_err(|e| format!("setting the read timeout: {e}"))?;
    stream
        .set_write_timeout(Some(REQUEST_TIMEOUT))
        .map_err(|e| format!("setting the write timeout: {e}"))?;
    stream
        .write_all(request)
        .map_err(|e| format!("sending the request: {e}"))?;
    let mut raw = Vec::new();
    stream
        .read_to_end(&mut raw)
        .map_err(|e| format!("reading the response: {e}"))?;
    Ok((stream, raw))
}

fn get(port: u16, target: &str) -> Result<HttpResponse, String> {
    http_request(
        port,
        format!("GET {target} HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n").as_bytes(),
    )
}

/// A `POST` with `body` (its length declared), as `fetch` sends one.
fn post_request(target: &str, body: &[u8]) -> Vec<u8> {
    let mut request = format!(
        "POST {target} HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
        body.len()
    )
    .into_bytes();
    request.extend_from_slice(body);
    request
}

fn post(port: u16, target: &str, body: &[u8]) -> Result<HttpResponse, String> {
    http_request(port, &post_request(target, body))
}

/// Checks one response's status, content type and exact body.
fn expect(
    label: &str,
    response: &HttpResponse,
    status: u16,
    content_type: &str,
    body: &[u8],
) -> Result<(), String> {
    if response.status != status {
        return Err(format!(
            "{label}: status {} (expected {status}); body: {}",
            response.status,
            String::from_utf8_lossy(&response.body)
        ));
    }
    if response.header("Content-Type") != Some(content_type) {
        return Err(format!(
            "{label}: Content-Type {:?} (expected {content_type:?})",
            response.header("Content-Type")
        ));
    }
    if response.header("Cache-Control") != Some("no-store") {
        return Err(format!(
            "{label}: Cache-Control {:?} (expected no-store)",
            response.header("Cache-Control")
        ));
    }
    let declared = response
        .header("Content-Length")
        .and_then(|value| value.parse::<usize>().ok());
    if declared != Some(response.body.len()) {
        return Err(format!(
            "{label}: Content-Length {declared:?} does not match the {} body bytes received",
            response.body.len()
        ));
    }
    if response.body != body {
        return Err(format!(
            "{label}: body differs from the expected bytes\n  got:      {}\n  expected: {}",
            String::from_utf8_lossy(&response.body),
            String::from_utf8_lossy(body)
        ));
    }
    Ok(())
}

/// Every HTTP contract the server documents, against the live port.
pub fn check_http_contract(port: u16, dashboard: &[u8]) -> Result<usize, String> {
    let json = "application/json";
    let html = "text/html; charset=utf-8";
    expect("GET /", &get(port, "/")?, 200, html, dashboard)?;
    expect(
        "GET /api/devices",
        &get(port, "/api/devices")?,
        200,
        json,
        DEVICES_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/devices?verbose=1 (query ignored)",
        &get(port, "/api/devices?verbose=1")?,
        200,
        json,
        DEVICES_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/status",
        &get(port, "/api/status")?,
        200,
        json,
        STATUS_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/updates",
        &get(port, "/api/updates")?,
        200,
        json,
        UPDATES_JSON.as_bytes(),
    )?;
    expect(
        "GET /nope",
        &get(port, "/nope")?,
        404,
        json,
        NOT_FOUND_JSON.as_bytes(),
    )?;
    expect(
        "GET /api (prefix only)",
        &get(port, "/api")?,
        404,
        json,
        NOT_FOUND_JSON.as_bytes(),
    )?;
    expect(
        "POST /api/status",
        &http_request(
            port,
            b"POST /api/status HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: 0\r\n\r\n",
        )?,
        405,
        json,
        METHOD_NOT_ALLOWED_JSON.as_bytes(),
    )?;
    expect(
        "DELETE /",
        &http_request(port, b"DELETE / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n")?,
        405,
        json,
        METHOD_NOT_ALLOWED_JSON.as_bytes(),
    )?;
    expect(
        "malformed request line",
        &http_request(port, b"GARBAGE\r\n\r\n")?,
        400,
        json,
        br#"{"error":"Bad request"}"#,
    )?;

    // Scan control, in the order the harness script answers: a pause that
    // every document reflects, an accepted start, the four documented
    // refusals, a control that throws (answered 500, the server still up), a
    // start whose request body must be skipped, and the wrong method or
    // path. The sequence ends scanning, which the browser render expects.
    let paused_devices = DEVICES_JSON.replacen(r#""scanning":true"#, r#""scanning":false"#, 1);
    expect(
        "POST /api/scan/stop",
        &post(port, "/api/scan/stop", b"")?,
        200,
        json,
        SCAN_STOPPED_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/status (paused)",
        &get(port, "/api/status")?,
        200,
        json,
        PAUSED_STATUS_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/devices (paused)",
        &get(port, "/api/devices")?,
        200,
        json,
        paused_devices.as_bytes(),
    )?;
    expect(
        "POST /api/scan/start (accepted)",
        &post(port, "/api/scan/start", b"")?,
        200,
        json,
        SCAN_STARTED_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/status (resumed)",
        &get(port, "/api/status")?,
        200,
        json,
        STATUS_JSON.as_bytes(),
    )?;
    for (label, body) in START_REFUSALS {
        expect(
            &format!("POST /api/scan/start ({label})"),
            &post(port, "/api/scan/start", b"")?,
            409,
            json,
            body.as_bytes(),
        )?;
    }
    expect(
        "POST /api/scan/start (the control throws)",
        &post(port, "/api/scan/start", b"")?,
        500,
        json,
        CONTROL_THREW_JSON.as_bytes(),
    )?;
    expect(
        "GET /api/status (the server survived)",
        &get(port, "/api/status")?,
        200,
        json,
        STATUS_JSON.as_bytes(),
    )?;
    // A body larger than the server's read buffers: without the skip it stays
    // unread in the socket and the close becomes a reset (which a client on
    // Android may see as a lost answer), so the close must be clean.
    let body = vec![b'x'; 64 * 1024];
    expect(
        "POST /api/scan/start with a 64 KiB request body",
        &http_request_clean_close(port, &post_request("/api/scan/start", &body))?,
        200,
        json,
        SCAN_STARTED_JSON.as_bytes(),
    )?;
    // A body declared beyond the server's cap is refused at once, without
    // waiting for bytes the client never sends.
    expect(
        "POST /api/scan/start declaring a 1 MiB body it never sends",
        &http_request(
            port,
            b"POST /api/scan/start HTTP/1.1\r\nHost: 127.0.0.1\r\nContent-Length: 1048576\r\nConnection: close\r\n\r\n",
        )?,
        413,
        json,
        br#"{"error":"Request body too large"}"#,
    )?;
    expect(
        "GET /api/scan/start",
        &get(port, "/api/scan/start")?,
        405,
        json,
        METHOD_NOT_ALLOWED_JSON.as_bytes(),
    )?;
    expect(
        "DELETE /api/scan/stop",
        &http_request(
            port,
            b"DELETE /api/scan/stop HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n",
        )?,
        405,
        json,
        METHOD_NOT_ALLOWED_JSON.as_bytes(),
    )?;
    expect(
        "POST /api/scan/other",
        &post(port, "/api/scan/other", b"")?,
        404,
        json,
        NOT_FOUND_JSON.as_bytes(),
    )?;
    expect(
        "POST /api/scan (prefix only)",
        &post(port, "/api/scan", b"")?,
        404,
        json,
        NOT_FOUND_JSON.as_bytes(),
    )?;
    Ok(27)
}

/// The whole command.
pub fn run(root: &Path) -> Result<(), String> {
    let (chromium, version) = dashboard::locate_chromium()?;
    println!("browser={} ({version})", chromium.display());

    println!("== building host bleradar-jni ==");
    let host_lib = crate::build_host_jni_library(root)?;
    let library_dir = host_lib.parent().ok_or_else(|| {
        format!(
            "host library has no parent directory: {}",
            host_lib.display()
        )
    })?;

    let dashboard_path = root.join(DASHBOARD_ASSET_PATH);
    let dashboard_bytes = fs::read(&dashboard_path)
        .map_err(|e| format!("reading {}: {e}", dashboard_path.display()))?;

    let temp_dir = crate::xtask_temp_dir("verify-api-live");
    let package_dir = temp_dir.join("src/com/hse/bleradar");
    let classes_dir = temp_dir.join("classes");
    crate::recreate_dirs(&[&package_dir, &classes_dir])?;
    let source_dir = root.join(JAVA_PACKAGE_DIR);
    let mut sources = Vec::new();
    for name in HOST_JAVA_SOURCES {
        let from = source_dir.join(name);
        let to = package_dir.join(name);
        fs::copy(&from, &to).map_err(|e| format!("copying {}: {e}", from.display()))?;
        sources.push(to);
    }
    let smoke = package_dir.join("ApiSmoke.java");
    fs::write(&smoke, api_smoke_java_source())
        .map_err(|e| format!("writing {}: {e}", smoke.display()))?;
    sources.push(smoke);
    // The "ok" scenario serves the manifest `release-manifest` would publish
    // for the committed APK: its acceptance by the real core is then a fact
    // of every run, not of a fixture.
    let apk_path = root.join(crate::apk_output_name());
    let artifact =
        fs::read(&apk_path).map_err(|e| format!("reading {}: {e}", apk_path.display()))?;
    let manifest_xml_path = root
        .join(crate::ANDROID_APP_DIR)
        .join("AndroidManifest.xml");
    let manifest_xml = fs::read_to_string(&manifest_xml_path)
        .map_err(|e| format!("reading {}: {e}", manifest_xml_path.display()))?;
    let (min_sdk, _) = crate::parse_uses_sdk(&manifest_xml)?;
    let release_manifest = crate::release_manifest_text(
        &artifact,
        &crate::release_artifact_url(),
        min_sdk,
        "verify-api-live",
    );
    let manifest_smoke = package_dir.join("ManifestSourceSmoke.java");
    fs::write(
        &manifest_smoke,
        manifest_source_smoke_java_source(&release_manifest),
    )
    .map_err(|e| format!("writing {}: {e}", manifest_smoke.display()))?;
    sources.push(manifest_smoke);

    println!(
        "== javac {} host-executable sources + ApiSmoke.java + ManifestSourceSmoke.java (no android.jar) ==",
        HOST_JAVA_SOURCES.len()
    );
    crate::run_status({
        let mut c = Command::new("javac");
        c.args(["-encoding", "UTF-8", "-d"]).arg(&classes_dir);
        c.args(&sources);
        c
    })?;

    println!("== java ApiSmoke: the real ApiHttpServer with fixture sources ==");
    let mut command = Command::new("java");
    command
        .arg(format!("-Djava.library.path={}", library_dir.display()))
        .arg("-cp")
        .arg(&classes_dir)
        .arg("com.hse.bleradar.ApiSmoke")
        .arg(&dashboard_path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit());
    let mut child = command
        .spawn()
        .map_err(|e| format!("failed to spawn java: {e}"))?;
    let stdout = child.stdout.take().ok_or("java stdout not captured")?;
    let (tx, rx) = mpsc::channel();
    thread::spawn(move || {
        let mut lines = BufReader::new(stdout).lines();
        if let Some(Ok(line)) = lines.next() {
            let _ = tx.send(line);
        }
    });
    let outcome = (|| -> Result<(), String> {
        let first = rx
            .recv_timeout(STARTUP_TIMEOUT)
            .map_err(|_| "the server did not report its port in time".to_string())?;
        let port: u16 = first
            .strip_prefix("port=")
            .and_then(|value| value.parse().ok())
            .ok_or_else(|| format!("unexpected first line from the server: {first:?}"))?;
        println!("server bound to http://127.0.0.1:{port}/");

        println!("== HTTP contract by real requests ==");
        let checks = check_http_contract(port, &dashboard_bytes)?;
        println!(
            "{checks} requests answered as documented; /api/devices, /api/status and /api/updates are byte-identical to the browser fixtures; scan control paused, resumed, refused four ways, survived a throwing control and skipped a request body"
        );

        println!("== headless Chromium renders the dashboard from the real server ==");
        let output_dir = root.join("target/api-live");
        let _ = fs::remove_dir_all(&output_dir);
        fs::create_dir_all(&output_dir)
            .map_err(|e| format!("creating {}: {e}", output_dir.display()))?;
        let dom = dashboard::render(
            &chromium,
            &format!("http://127.0.0.1:{port}/"),
            &output_dir.join("profile"),
            None,
        )?;
        let dom_path = output_dir.join("healthy.html");
        fs::write(&dom_path, &dom).map_err(|e| format!("writing {}: {e}", dom_path.display()))?;
        let polls = dashboard::check_dom(Scenario::Healthy, &dom)
            .map_err(|e| format!("{e} (rendered DOM kept at {})", dom_path.display()))?;
        println!("rendered page ok: polls={polls}, every device row present in the server's order");
        Ok(())
    })();

    // Closing stdin tells the harness to stop; give it a moment, then insist.
    drop(child.stdin.take());
    let deadline = Instant::now() + Duration::from_secs(15);
    let status = loop {
        if let Some(status) = child
            .try_wait()
            .map_err(|e| format!("waiting for java: {e}"))?
        {
            break Some(status);
        }
        if Instant::now() >= deadline {
            let _ = child.kill();
            let _ = child.wait();
            break None;
        }
        thread::sleep(Duration::from_millis(50));
    };
    outcome?;
    match status {
        Some(status) if status.success() => {}
        Some(status) => return Err(format!("the server exited with {status} after the checks")),
        None => return Err("the server did not stop after stdin closed and was killed".to_string()),
    }

    println!(
        "== java ManifestSourceSmoke: the real ReleaseManifestSource against a scripted server =="
    );
    let output = Command::new("java")
        .arg(format!("-Djava.library.path={}", library_dir.display()))
        .arg("-cp")
        .arg(&classes_dir)
        .arg("com.hse.bleradar.ManifestSourceSmoke")
        .output()
        .map_err(|e| format!("failed to spawn java: {e}"))?;
    let report = String::from_utf8_lossy(&output.stdout);
    if !output.status.success() {
        return Err(format!(
            "ManifestSourceSmoke exited with {}:\n{report}{}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let scenarios = check_manifest_source_report(&report)?;
    print!("{report}");
    println!(
        "{scenarios} fetches classified as documented and dispositioned by the Rust core through the real .so; the accepted manifest is the release manifest of {} ({} bytes)",
        apk_path.display(),
        artifact.len()
    );
    // The emulator's upgrade proof rests on a stand-in github.com (a TLS
    // server on a generated trust anchor behind a CONNECT proxy); its host
    // side is proven here, on this JVM and curl, before any emulator boots.
    println!("== the upgrade proof's stand-in release host, through its proxy over TLS (curl) ==");
    let stand_in = crate::updateproof::self_check(
        &crate::xtask_temp_dir("verify-api-live-stand-in"),
        &release_manifest,
        &apk_path,
    )?;
    println!("{stand_in}");
    println!(
        "verify-api-live: real ApiHttpServer + real dashboard + headless Chromium + the manifest source + the upgrade proof's stand-in, all green"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn java_string_literals_escape_what_java_needs() {
        assert_eq!(
            java_string_literal("a\"b\\c\n\td"),
            "\"a\\\"b\\\\c\\n\\td\""
        );
        assert_eq!(java_string_literal(""), "\"\"");
        let source = manifest_source_smoke_java_source("version_code = 1\n");
        assert!(source.contains("private static final String MANIFEST = \"version_code = 1\\n\";"));
        assert!(!source.contains("__OK_MANIFEST__"));
    }

    #[test]
    fn the_manifest_source_report_is_checked_scenario_by_scenario() {
        let good = "scenario=ok status=200 failure=0 accepted=true disposition=0 detail=HTTP 200, 231 bytes\n\
                    scenario=missing status=404 failure=0 accepted=false disposition=2 detail=HTTP 404\n\
                    scenario=down status=503 failure=0 accepted=false disposition=1 detail=HTTP 503\n\
                    scenario=redirect status=301 failure=0 accepted=false disposition=2 detail=HTTP 301\n\
                    scenario=large status=200 failure=2 accepted=false disposition=2 detail=HTTP 200, body over 16384 bytes\n\
                    scenario=junk status=200 failure=3 accepted=false disposition=2 detail=HTTP 200, 17 bytes\n\
                    scenario=slow status=0 failure=1 accepted=false disposition=1 detail=SocketTimeoutException: Read timed out\n\
                    scenario=refused status=0 failure=1 accepted=false disposition=1 detail=ConnectException: Connection refused\n\
                    scenario=malformed status=0 failure=1 accepted=false disposition=1 detail=MalformedURLException: no protocol: not a url\n";
        assert_eq!(check_manifest_source_report(good), Ok(9));
        let wrong = good.replace(
            "scenario=down status=503 failure=0 accepted=false disposition=1",
            "scenario=down status=503 failure=0 accepted=false disposition=2",
        );
        assert!(
            check_manifest_source_report(&wrong)
                .unwrap_err()
                .contains("scenario down")
        );
        let missing = good.replace("scenario=refused", "scenario=refused-not-run");
        assert!(
            check_manifest_source_report(&missing)
                .unwrap_err()
                .contains("unexpected scenario")
        );
        let short: String = good
            .lines()
            .take(8)
            .map(|line| format!("{line}\n"))
            .collect();
        assert!(
            check_manifest_source_report(&short)
                .unwrap_err()
                .contains("not reported: malformed")
        );
        let twice = format!("{good}{}", good.lines().next().unwrap());
        assert!(
            check_manifest_source_report(&twice)
                .unwrap_err()
                .contains("twice")
        );
    }

    #[test]
    fn responses_are_parsed_into_status_headers_and_body() {
        let raw = b"HTTP/1.1 404 Not Found\r\nContent-Type: application/json\r\nContent-Length: 21\r\n\r\n{\"error\":\"Not found\"}";
        let response = parse_http_response(raw).unwrap();
        assert_eq!(response.status, 404);
        assert_eq!(response.header("content-type"), Some("application/json"));
        assert_eq!(response.body, br#"{"error":"Not found"}"#);
        assert!(parse_http_response(b"HTTP/1.1 200 OK\r\n").is_err());
        assert!(parse_http_response(b"HTTP/1.1 nope\r\n\r\n").is_err());
    }

    #[test]
    fn expectation_names_every_mismatch() {
        let ok = HttpResponse {
            status: 200,
            headers: vec![
                ("Content-Type".to_string(), "application/json".to_string()),
                ("Content-Length".to_string(), "2".to_string()),
                ("Cache-Control".to_string(), "no-store".to_string()),
            ],
            body: b"{}".to_vec(),
        };
        assert_eq!(expect("x", &ok, 200, "application/json", b"{}"), Ok(()));
        assert!(
            expect("x", &ok, 404, "application/json", b"{}")
                .unwrap_err()
                .contains("status 200")
        );
        assert!(
            expect("x", &ok, 200, "text/html", b"{}")
                .unwrap_err()
                .contains("Content-Type")
        );
        assert!(
            expect("x", &ok, 200, "application/json", b"[]")
                .unwrap_err()
                .contains("body differs")
        );
        let mut short = HttpResponse {
            status: 200,
            headers: ok.headers.clone(),
            body: b"{}}".to_vec(),
        };
        assert!(
            expect("x", &short, 200, "application/json", b"{}}")
                .unwrap_err()
                .contains("Content-Length")
        );
        short.headers.retain(|(name, _)| name != "Cache-Control");
        assert!(
            expect("x", &short, 200, "application/json", b"{}}")
                .unwrap_err()
                .contains("Cache-Control")
        );
    }

    #[test]
    fn the_harness_fixtures_are_the_browser_fixtures() {
        // Every value the harness feeds the real server must appear in the
        // fixture the browser scenarios use, so the byte-for-byte comparison
        // in check_http_contract is meaningful.
        let harness = api_smoke_java_source();
        for value in [
            "AA:BB:CC:DD:EE:01",
            "Tag Alpha",
            "1.234",
            "-61.4",
            "12345",
            "Beacon Delta",
            "3_723_000L",
            "1_757_600_000_000L",
            "1_757_686_400_000L",
        ] {
            assert!(harness.contains(value), "{value}");
        }
        assert!(DEVICES_JSON.contains(r#""last_seen_ago_ms":420"#));
        assert!(DEVICES_JSON.contains(r#""timestamp_ms":1757700000000"#));
        assert!(STATUS_JSON.contains(r#""uptime_ms":3723000"#));
        assert!(UPDATES_JSON.contains(r#""retry_count":2"#));
    }

    #[test]
    fn the_scripted_control_answers_every_documented_outcome() {
        // The 409 bodies the checks expect must be the labels the server
        // writes, and the script must reach every outcome the interface
        // declares (plus the throw), so the checks cannot drift from either.
        let java =
            include_str!("../../android/app/src/main/java/com/hse/bleradar/ApiHttpServer.java");
        let control =
            include_str!("../../android/app/src/main/java/com/hse/bleradar/ScanControl.java");
        for (_, body) in START_REFUSALS {
            let message = body
                .trim_start_matches(r#"{"error":""#)
                .trim_end_matches(r#""}"#);
            assert!(java.contains(&format!("\"{message}\"")), "{message}");
        }
        let harness = api_smoke_java_source();
        for outcome in [
            "START_ACCEPTED",
            "START_PERMISSIONS_MISSING",
            "START_BLUETOOTH_OFF",
            "START_UNAVAILABLE",
            "START_BACKGROUND_RESTRICTED",
        ] {
            assert!(control.contains(&format!("int {outcome} = ")), "{outcome}");
            assert!(harness.contains(outcome), "{outcome}");
        }
        assert!(harness.contains("throw new IllegalStateException"));
        assert!(CONTROL_THREW_JSON.contains("IllegalStateException"));
        assert_eq!(
            PAUSED_STATUS_JSON,
            STATUS_JSON
                .replace(r#""scanning":true"#, r#""scanning":false"#)
                .replace(r#""uptime_ms":3723000"#, r#""uptime_ms":0"#)
        );
    }
}
