//! `cargo xtask verify-android-unit`: the app's unit tests
//! (`android/app/src/test/java/com/hse/bleradar`) executed on the host JVM
//! against the real host `bleradar-jni` library.
//!
//! The tests are written against `org.junit.Test` and `org.junit.Assert`,
//! but no JUnit jar and no Gradle project exist in this tree, so until
//! decision #98 no test in that directory had ever run. Rather than vendor a
//! framework, xtask generates the two classes the tests import — the `@Test`
//! marker and the `Assert` statics they call, with JUnit's overload set so
//! `javac` resolves every call the way JUnit would — and a reflection runner
//! that instantiates each class and invokes every `@Test` method. The
//! directory may hold only the classes listed in [`HOST_TEST_CLASSES`], each
//! with its pinned method count, so a dormant test cannot come back.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::process::Command;

use crate::apilive::{HOST_JAVA_SOURCES, JAVA_PACKAGE_DIR};

/// Where the app's unit tests live, relative to the repository root.
pub const TEST_PACKAGE_DIR: &str = "android/app/src/test/java/com/hse/bleradar";

/// Every test class in [`TEST_PACKAGE_DIR`] with the number of `@Test`
/// methods it carries. The runner executes exactly these, and the directory
/// may contain nothing else: a test file that is not listed here is a test
/// that would never run — the state every file in that directory was in
/// before decision #98 — so [`run`] refuses it. The count is pinned so a
/// test method that vanishes is noticed too.
pub const HOST_TEST_CLASSES: &[(&str, usize)] = &[
    ("BlipTest.java", 14),
    ("DeviceHistoryTest.java", 6),
    ("ReleaseManifestTest.java", 50),
];

/// The generated runner's class.
pub const RUNNER_CLASS: &str = "bleradar.xtask.JUnitLiteRunner";

/// `org.junit.Test`, as far as the tests use it.
pub const JUNIT_TEST_SOURCE: &str = r#"package org.junit;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The JUnit 4 marker the app's tests put on every test method, as far as
 * they use it: no {@code expected}, no {@code timeout} — a test that needed
 * either fails to compile here instead of running with another meaning.
 * Generated by {@code cargo xtask verify-android-unit}; no JUnit jar exists
 * in this tree.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface Test {
}
"#;

/// `org.junit.Assert`: the message-first assertions the tests call.
pub const JUNIT_ASSERT_SOURCE: &str = r#"package org.junit;

/**
 * The JUnit 4 assertions the app's tests call, with JUnit's overload set for
 * them so {@code javac} resolves every call as JUnit would: an {@code int}
 * pair lands on the {@code long} overload, a boxed pair on {@code Object},
 * a floating-point pair without a delta on the deprecated overload that
 * always fails, and a {@code float} pair given to {@code assertNotEquals}
 * widens to the {@code double} overload because JUnit 4 has no message-first
 * {@code float} one. Generated by {@code cargo xtask verify-android-unit};
 * no JUnit jar exists in this tree.
 */
public final class Assert {

    private Assert() {
    }

    public static void fail(String message) {
        throw new AssertionError(message);
    }

    public static void assertTrue(String message, boolean condition) {
        if (!condition) {
            fail(message);
        }
    }

    public static void assertFalse(String message, boolean condition) {
        if (condition) {
            fail(message);
        }
    }

    public static void assertNull(String message, Object actual) {
        if (actual != null) {
            fail(message + " expected null, but was:<" + actual + ">");
        }
    }

    public static void assertNotNull(String message, Object actual) {
        if (actual == null) {
            fail(message + " expected not null");
        }
    }

    public static void assertEquals(String message, long expected, long actual) {
        if (expected != actual) {
            fail(mismatch(message, expected, actual));
        }
    }

    public static void assertEquals(String message, Object expected, Object actual) {
        if (!same(expected, actual)) {
            fail(mismatch(message, expected, actual));
        }
    }

    public static void assertEquals(String message, double expected, double actual, double delta) {
        if (!within(expected, actual, delta)) {
            fail(mismatch(message, expected, actual));
        }
    }

    public static void assertEquals(String message, float expected, float actual, float delta) {
        if (!within(expected, actual, delta)) {
            fail(mismatch(message, expected, actual));
        }
    }

    /** JUnit's deprecated overload: always fails, so a delta is never forgotten. */
    @Deprecated
    public static void assertEquals(String message, double expected, double actual) {
        fail("Use assertEquals(expected, actual, delta) to compare floating-point numbers");
    }

    public static void assertNotEquals(String message, long unexpected, long actual) {
        if (unexpected == actual) {
            fail(unexpectedly(message, actual));
        }
    }

    public static void assertNotEquals(String message, Object unexpected, Object actual) {
        if (same(unexpected, actual)) {
            fail(unexpectedly(message, actual));
        }
    }

    public static void assertNotEquals(String message, double unexpected, double actual, double delta) {
        if (within(unexpected, actual, delta)) {
            fail(unexpectedly(message, actual));
        }
    }

    private static boolean same(Object a, Object b) {
        return a == null ? b == null : a.equals(b);
    }

    private static boolean within(double expected, double actual, double delta) {
        return Double.compare(expected, actual) == 0 || Math.abs(expected - actual) <= delta;
    }

    private static boolean within(float expected, float actual, float delta) {
        return Float.compare(expected, actual) == 0 || Math.abs(expected - actual) <= delta;
    }

    private static String mismatch(String message, Object expected, Object actual) {
        return message + " expected:<" + expected + "> but was:<" + actual + ">";
    }

    private static String unexpectedly(String message, Object actual) {
        return message + " actual value was the unexpected:<" + actual + ">";
    }
}
"#;

/// The runner: JUnit 4's behaviour for the subset the tests use.
pub const RUNNER_SOURCE: &str = r##"package bleradar.xtask;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Runs the app's unit tests the way JUnit 4 would for the subset they use: a
 * fresh instance per test method, every public method marked {@code @Test}
 * invoked in name order, any throwable a failure. Reports one line per class
 * ({@code class <name> tests=N failed=M}) and a summary, and exits 1 on any
 * failure. Refuses to run while the native core is unavailable: half of
 * {@code ReleaseManifestTest} asserts {@code null} results, which a JVM
 * without {@code libbleradar_jni.so} would produce for the wrong reason.
 * Generated by {@code cargo xtask verify-android-unit}.
 */
public final class JUnitLiteRunner {

    private JUnitLiteRunner() {
    }

    public static void main(String[] args) throws Exception {
        // The tests exercise the app's warning paths on purpose; keep those
        // log lines out of the report.
        Logger.getLogger("").setLevel(Level.SEVERE);
        if (!com.hse.bleradar.NativeRadar.isAvailable()) {
            System.out.println("native core=unavailable");
            System.exit(3);
        }
        System.out.println("native core=available");
        int total = 0;
        int failed = 0;
        for (String name : args) {
            Class<?> cls = Class.forName(name);
            Method[] methods = cls.getMethods();
            Arrays.sort(methods, Comparator.comparing(Method::getName));
            int classTests = 0;
            int classFailed = 0;
            for (Method method : methods) {
                if (!method.isAnnotationPresent(org.junit.Test.class)) {
                    continue;
                }
                classTests++;
                try {
                    Object instance = cls.getDeclaredConstructor().newInstance();
                    method.invoke(instance);
                    System.out.println("ok   " + cls.getSimpleName() + "#" + method.getName());
                } catch (InvocationTargetException e) {
                    // The constructor or the test method threw: that throwable
                    // is the failure, as under JUnit.
                    classFailed++;
                    System.out.println("FAIL " + cls.getSimpleName() + "#" + method.getName() + ": " + e.getCause());
                } catch (ReflectiveOperationException | RuntimeException e) {
                    // No accessible no-arg constructor, or the reflection
                    // itself failed: the test cannot run, so it fails.
                    classFailed++;
                    System.out.println("FAIL " + cls.getSimpleName() + "#" + method.getName() + ": " + e);
                }
            }
            System.out.println("class " + cls.getName() + " tests=" + classTests + " failed=" + classFailed);
            total += classTests;
            failed += classFailed;
        }
        System.out.println("summary tests=" + total + " failed=" + failed);
        System.exit(failed == 0 ? 0 : 1);
    }
}
"##;

/// The fully qualified class a test file declares.
fn test_class_name(file: &str) -> String {
    format!("com.hse.bleradar.{}", file.trim_end_matches(".java"))
}

/// What is wrong with the test directory's file set: a `.java` file the
/// runner does not execute (a test that would never run), or a listed class
/// that is gone. Sorted; empty when the directory is exactly the list.
pub fn test_directory_mismatches(files: &[String]) -> Vec<String> {
    let mut mismatches = Vec::new();
    for file in files {
        if file.ends_with(".java") && !HOST_TEST_CLASSES.iter().any(|(name, _)| name == file) {
            mismatches.push(format!(
                "{file}: not run by verify-android-unit (list it in HOST_TEST_CLASSES with its test count, or remove it)"
            ));
        }
    }
    for (name, _) in HOST_TEST_CLASSES {
        if !files.iter().any(|file| file == name) {
            mismatches.push(format!(
                "{name}: listed in HOST_TEST_CLASSES but missing from {TEST_PACKAGE_DIR}"
            ));
        }
    }
    mismatches.sort();
    mismatches
}

/// What the runner reported: whether the native core loaded, each class's
/// `(tests, failed)` counts, and the summary's `(tests, failed)` counts.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct RunnerReport {
    /// Whether the runner printed `native core=available` before any test.
    pub native_available: bool,
    /// Per fully qualified test class: `(tests run, tests failed)`.
    pub classes: BTreeMap<String, (usize, usize)>,
    /// The `summary tests=N failed=M` line as `(N, M)`, when printed.
    pub summary: Option<(usize, usize)>,
}

/// `tests=N failed=M` → `(N, M)`.
fn counts(rest: &str) -> Option<(usize, usize)> {
    let (tests, failed) = rest.trim().split_once(' ')?;
    Some((
        tests.strip_prefix("tests=")?.parse().ok()?,
        failed.strip_prefix("failed=")?.parse().ok()?,
    ))
}

/// Reads the runner's report lines; anything else (the per-test lines, a
/// stray stack trace) is ignored.
pub fn parse_runner_report(output: &str) -> RunnerReport {
    let mut report = RunnerReport::default();
    for line in output.lines().map(str::trim) {
        if line == "native core=available" {
            report.native_available = true;
        } else if let Some(rest) = line.strip_prefix("class ") {
            if let Some((class, rest)) = rest.split_once(' ')
                && let Some(counts) = counts(rest)
            {
                report.classes.insert(class.to_string(), counts);
            }
        } else if let Some(rest) = line.strip_prefix("summary ") {
            report.summary = counts(rest);
        }
    }
    report
}

/// Requires the report to show the native core loaded, every listed class
/// run with its pinned count and no failure, and the summary to agree;
/// returns the total. The failures the runner printed are quoted.
pub fn check_runner_report(output: &str) -> Result<usize, String> {
    let report = parse_runner_report(output);
    if !report.native_available {
        return Err(
            "the runner did not load the native core (no `native core=available` line); ReleaseManifestTest's null-result half would pass vacuously".to_string(),
        );
    }
    let mut total = 0;
    for (file, expected) in HOST_TEST_CLASSES {
        let class = test_class_name(file);
        let (tests, failed) = report
            .classes
            .get(&class)
            .copied()
            .ok_or_else(|| format!("{class}: no report line from the runner"))?;
        if failed != 0 {
            let failures: Vec<&str> = output
                .lines()
                .filter(|line| line.starts_with("FAIL "))
                .collect();
            return Err(format!(
                "{class}: {failed} of {tests} tests failed:\n  {}",
                failures.join("\n  ")
            ));
        }
        if tests != *expected {
            return Err(format!(
                "{class}: {tests} tests ran, {expected} pinned in HOST_TEST_CLASSES (a test method was added or removed; update the pin)"
            ));
        }
        total += tests;
    }
    match report.summary {
        Some((tests, 0)) if tests == total => Ok(total),
        other => Err(format!(
            "the runner's summary {other:?} does not match the {total} tests its classes reported"
        )),
    }
}

/// Builds the host library, compiles the host-executable sources with the
/// listed test classes and the generated shim, runs the tests, and requires
/// the report described on [`check_runner_report`].
pub fn run(root: &Path) -> Result<(), String> {
    println!("== building host bleradar-jni ==");
    let host_lib = crate::build_host_jni_library(root)?;
    let library_dir = host_lib.parent().ok_or_else(|| {
        format!(
            "host library has no parent directory: {}",
            host_lib.display()
        )
    })?;

    let test_dir = root.join(TEST_PACKAGE_DIR);
    let mut files: Vec<String> = fs::read_dir(&test_dir)
        .map_err(|e| format!("listing {}: {e}", test_dir.display()))?
        .filter_map(Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    files.sort();
    let mismatches = test_directory_mismatches(&files);
    if !mismatches.is_empty() {
        return Err(format!(
            "{TEST_PACKAGE_DIR} does not match the classes verify-android-unit runs:\n  {}",
            mismatches.join("\n  ")
        ));
    }

    let temp_dir = crate::xtask_temp_dir("verify-android-unit");
    let package_dir = temp_dir.join("src/com/hse/bleradar");
    let junit_dir = temp_dir.join("src/org/junit");
    let runner_dir = temp_dir.join("src/bleradar/xtask");
    let classes_dir = temp_dir.join("classes");
    crate::recreate_dirs(&[&package_dir, &junit_dir, &runner_dir, &classes_dir])?;
    let mut sources = Vec::new();
    let source_dir = root.join(JAVA_PACKAGE_DIR);
    for name in HOST_JAVA_SOURCES {
        let from = source_dir.join(name);
        let to = package_dir.join(name);
        fs::copy(&from, &to).map_err(|e| format!("copying {}: {e}", from.display()))?;
        sources.push(to);
    }
    for (name, _) in HOST_TEST_CLASSES {
        let from = test_dir.join(name);
        let to = package_dir.join(name);
        fs::copy(&from, &to).map_err(|e| format!("copying {}: {e}", from.display()))?;
        sources.push(to);
    }
    for (path, text) in [
        (junit_dir.join("Test.java"), JUNIT_TEST_SOURCE),
        (junit_dir.join("Assert.java"), JUNIT_ASSERT_SOURCE),
        (runner_dir.join("JUnitLiteRunner.java"), RUNNER_SOURCE),
    ] {
        fs::write(&path, text).map_err(|e| format!("writing {}: {e}", path.display()))?;
        sources.push(path);
    }

    println!(
        "== javac {} host-executable sources + {} test classes + the JUnit-subset shim and runner (no android.jar, no junit.jar) ==",
        HOST_JAVA_SOURCES.len(),
        HOST_TEST_CLASSES.len()
    );
    crate::run_status({
        let mut c = Command::new("javac");
        c.args(["-encoding", "UTF-8", "-d"]).arg(&classes_dir);
        c.args(&sources);
        c
    })?;

    let classes: Vec<String> = HOST_TEST_CLASSES
        .iter()
        .map(|(file, _)| test_class_name(file))
        .collect();
    println!("== java {RUNNER_CLASS}: {} ==", classes.join(", "));
    let output = Command::new("java")
        .arg(format!("-Djava.library.path={}", library_dir.display()))
        .arg("-cp")
        .arg(&classes_dir)
        .arg(RUNNER_CLASS)
        .args(&classes)
        .output()
        .map_err(|e| format!("failed to run java: {e}"))?;
    let stdout = String::from_utf8_lossy(&output.stdout);
    for line in stdout.lines().filter(|line| !line.starts_with("ok   ")) {
        println!("  {line}");
    }
    let checked = check_runner_report(&stdout);
    if !output.status.success() {
        return Err(match checked {
            Err(e) => e,
            Ok(_) => format!(
                "the runner exited with {} although its report shows no failure:\n{stdout}\n{}",
                output.status,
                String::from_utf8_lossy(&output.stderr)
            ),
        });
    }
    let total = checked?;
    println!(
        "verify-android-unit: {total} tests in {} classes passed on the host JVM against the real native core",
        HOST_TEST_CLASSES.len()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn report(blip: (usize, usize), manifest: (usize, usize), native: bool) -> String {
        let mut text = String::new();
        if native {
            text.push_str("native core=available\n");
        }
        text.push_str("ok   BlipTest#address_is_immutable\n");
        if blip.1 > 0 {
            text.push_str("FAIL BlipTest#angle_is_in_valid_range: java.lang.AssertionError: Angle should be less than 360\n");
        }
        text.push_str(&format!(
            "class com.hse.bleradar.BlipTest tests={} failed={}\n",
            blip.0, blip.1
        ));
        // The other pinned classes report their pinned count, all passing.
        let history = HOST_TEST_CLASSES
            .iter()
            .find(|(name, _)| *name == "DeviceHistoryTest.java")
            .map_or(0, |(_, count)| *count);
        text.push_str(&format!(
            "class com.hse.bleradar.DeviceHistoryTest tests={history} failed=0\n"
        ));
        text.push_str(&format!(
            "class com.hse.bleradar.ReleaseManifestTest tests={} failed={}\n",
            manifest.0, manifest.1
        ));
        text.push_str(&format!(
            "summary tests={} failed={}\n",
            blip.0 + history + manifest.0,
            blip.1 + manifest.1
        ));
        text
    }

    #[test]
    fn the_test_directory_must_be_exactly_the_classes_the_runner_executes() {
        let exact: Vec<String> = HOST_TEST_CLASSES
            .iter()
            .map(|(name, _)| name.to_string())
            .collect();
        assert!(test_directory_mismatches(&exact).is_empty());

        let mut with_extras = exact.clone();
        with_extras.push("MainActivityTest.java".to_string());
        with_extras.push("notes.txt".to_string());
        assert_eq!(
            test_directory_mismatches(&with_extras),
            vec![
                "MainActivityTest.java: not run by verify-android-unit (list it in HOST_TEST_CLASSES with its test count, or remove it)".to_string()
            ]
        );

        let missing: Vec<String> = exact[1..].to_vec();
        assert_eq!(
            test_directory_mismatches(&missing),
            vec![format!(
                "BlipTest.java: listed in HOST_TEST_CLASSES but missing from {TEST_PACKAGE_DIR}"
            )]
        );
    }

    #[test]
    fn the_runner_report_is_held_to_the_pinned_counts_the_native_core_and_zero_failures() {
        let pinned = |file: &str| {
            HOST_TEST_CLASSES
                .iter()
                .find(|(name, _)| *name == file)
                .map(|(_, count)| *count)
                .unwrap()
        };
        let (blip, manifest) = (pinned("BlipTest.java"), pinned("ReleaseManifestTest.java"));
        let total = blip + pinned("DeviceHistoryTest.java") + manifest;
        let good = report((blip, 0), (manifest, 0), true);
        assert_eq!(check_runner_report(&good), Ok(total));
        let parsed = parse_runner_report(&good);
        assert!(parsed.native_available);
        assert_eq!(parsed.summary, Some((total, 0)));

        let vacuous = check_runner_report(&report((blip, 0), (manifest, 0), false)).unwrap_err();
        assert!(
            vacuous.contains("did not load the native core"),
            "{vacuous}"
        );

        let failing = check_runner_report(&report((blip, 1), (manifest, 0), true)).unwrap_err();
        assert!(
            failing.contains("1 of") && failing.contains("FAIL BlipTest#angle_is_in_valid_range"),
            "{failing}"
        );

        let drifted = check_runner_report(&report((blip, 0), (manifest + 1, 0), true)).unwrap_err();
        assert!(drifted.contains("pinned in HOST_TEST_CLASSES"), "{drifted}");

        let truncated =
            "native core=available\nclass com.hse.bleradar.BlipTest tests=14 failed=0\n";
        assert!(
            check_runner_report(truncated)
                .unwrap_err()
                .contains("no report line")
        );

        let mut disagreeing = good.clone();
        disagreeing.push_str("summary tests=1 failed=0\n");
        assert!(
            check_runner_report(&disagreeing)
                .unwrap_err()
                .contains("summary")
        );
    }

    #[test]
    fn the_generated_shim_declares_the_junit_subset_the_tests_call() {
        for signature in [
            "void fail(String message)",
            "void assertTrue(String message, boolean condition)",
            "void assertFalse(String message, boolean condition)",
            "void assertNull(String message, Object actual)",
            "void assertNotNull(String message, Object actual)",
            "void assertEquals(String message, long expected, long actual)",
            "void assertEquals(String message, Object expected, Object actual)",
            "void assertEquals(String message, double expected, double actual, double delta)",
            "void assertEquals(String message, float expected, float actual, float delta)",
            "void assertNotEquals(String message, long unexpected, long actual)",
            "void assertNotEquals(String message, Object unexpected, Object actual)",
            "void assertNotEquals(String message, double unexpected, double actual, double delta)",
        ] {
            assert!(JUNIT_ASSERT_SOURCE.contains(signature), "{signature}");
        }
        // JUnit 4 has no message-first float assertNotEquals: a float pair must
        // widen to the double overload here as it does there.
        assert!(!JUNIT_ASSERT_SOURCE.contains("assertNotEquals(String message, float"));
        assert!(JUNIT_TEST_SOURCE.contains("@Retention(RetentionPolicy.RUNTIME)"));
        assert!(RUNNER_SOURCE.contains("native core=available"));
        assert!(RUNNER_SOURCE.contains(&format!(
            "class {}",
            RUNNER_CLASS.rsplit('.').next().unwrap()
        )));
        assert_eq!(
            test_class_name("BlipTest.java"),
            "com.hse.bleradar.BlipTest"
        );
    }
}
