//! The host side of the emulator's upgrade proof: a stand-in for
//! `github.com` that the app's production release URL reaches unchanged.
//!
//! The app fetches `UpdateCheckService.RELEASE_MANIFEST_URL` and, when the
//! manifest names a newer version, downloads the artifact the manifest points
//! at — both on `https://github.com/...`, which neither this sandbox nor CI
//! can publish to. So the proof stands a server up *for that name*: a JDK
//! `HttpsServer` (generated Java, run on the proof's JDK) on a `keytool`
//! certificate issued for `github.com`, answering the release URL's redirect,
//! the successor's manifest and its APK; a `CONNECT` proxy (this module,
//! `std::net`) that relays only `github.com:443` to that server and is set as
//! the guest's global HTTP proxy; and the certificate as a system trust
//! anchor in the guest — Android 14 keeps the system store in the Conscrypt
//! APEX, so it is shadowed by a tmpfs copy carrying one more file, in every
//! zygote's mount namespace, before the app is launched. The app and its
//! `DownloadManager` then talk to the real hostname over real TLS, and every
//! request the stand-in answers is logged for the report.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{Shutdown, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::{Arc, Mutex, mpsc};
use std::thread;
use std::time::{Duration, Instant};

/// The name the app's release URL carries and the certificate is issued for.
pub const RELEASE_HOST: &str = "github.com";
/// The proof's keystore password: a throw-away key for one emulator run.
pub const KEYSTORE_PASSWORD: &str = "upgrade-proof";
const KEY_ALIAS: &str = "github";
/// How long the stand-in server may take to report its port.
const SERVER_STARTUP_TIMEOUT: Duration = Duration::from_secs(30);
/// Where the guest's shadow copy of the system trust store lives and what it shadows.
pub const GUEST_CACERTS_COPY: &str = "/data/local/tmp/cacerts-copy";
pub const GUEST_CACERTS_DIR: &str = "/apex/com.android.conscrypt/cacerts";
/// Where the certificate is pushed before the script copies it in.
pub const GUEST_PUSH_DIR: &str = "/data/local/tmp";
/// The host as the guest reaches it: the emulator's alias for the host loopback.
pub const GUEST_HOST_ALIAS: &str = "10.0.2.2";

/// The generated stand-in: one `HttpsServer` on the proof's certificate,
/// answering exactly three paths — the release URL's redirect (as GitHub
/// answers a `releases/latest/download/...` URL), the successor's manifest
/// and its APK — and `404` for anything else, one log line per request.
/// Arguments: keystore, password, host name, latest path, manifest path,
/// manifest file, APK path, APK file. Runs until stdin closes.
pub const RELEASE_HOST_JAVA_SOURCE: &str = r#"import com.sun.net.httpserver.HttpsConfigurator;
import com.sun.net.httpserver.HttpsServer;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.KeyStore;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;

/**
 * The stand-in release host of {@code cargo xtask verify-android-emulator}'s
 * upgrade proof: what {@code github.com} answers the app for its release
 * manifest and the artifact it names, served on this host over TLS with a
 * certificate the guest was made to trust. Generated by xtask.
 */
public final class ReleaseHost {

    private ReleaseHost() {
    }

    public static void main(String[] args) throws Exception {
        String keystore = args[0];
        char[] password = args[1].toCharArray();
        String host = args[2];
        String latestPath = args[3];
        String manifestPath = args[4];
        byte[] manifest = Files.readAllBytes(Paths.get(args[5]));
        String apkPath = args[6];
        byte[] apk = Files.readAllBytes(Paths.get(args[7]));

        KeyStore store = KeyStore.getInstance("PKCS12");
        try (InputStream in = new FileInputStream(keystore)) {
            store.load(in, password);
        }
        KeyManagerFactory keys = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        keys.init(store, password);
        SSLContext tls = SSLContext.getInstance("TLS");
        tls.init(keys.getKeyManagers(), null, null);

        HttpsServer server = HttpsServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.setHttpsConfigurator(new HttpsConfigurator(tls));
        server.createContext("/", exchange -> {
            String path = exchange.getRequestURI().getPath();
            String method = exchange.getRequestMethod();
            int status;
            byte[] body = new byte[0];
            if (path.equals(latestPath)) {
                status = 302;
                exchange.getResponseHeaders().add("Location", "https://" + host + manifestPath);
            } else if (path.equals(manifestPath)) {
                status = 200;
                body = manifest;
                exchange.getResponseHeaders().add("Content-Type", "text/plain; charset=utf-8");
            } else if (path.equals(apkPath)) {
                status = 200;
                body = apk;
                exchange.getResponseHeaders().add("Content-Type", "application/vnd.android.package-archive");
            } else {
                status = 404;
            }
            if (method.equals("HEAD") || body.length == 0) {
                exchange.sendResponseHeaders(status, -1);
                exchange.close();
            } else {
                exchange.sendResponseHeaders(status, body.length);
                try (OutputStream out = exchange.getResponseBody()) {
                    out.write(body);
                }
            }
            System.out.println("request " + method + " " + path + " -> " + status);
            System.out.flush();
        });
        server.start();
        System.out.println("port=" + server.getAddress().getPort());
        System.out.flush();
        while (System.in.read() != -1) {
            // The proof closes stdin to stop the server.
        }
        server.stop(0);
    }
}
"#;

/// The proof's certificate: a PKCS#12 keystore the stand-in serves with, the
/// certificate as PEM, and the file name Android's trust store gives it (the
/// OpenSSL `subject_hash_old` of its subject, then `.0`).
pub struct TrustAnchor {
    pub keystore: PathBuf,
    pub pem: PathBuf,
    pub android_name: String,
}

/// Generates the certificate for [`RELEASE_HOST`] with `keytool` (self-signed,
/// RSA 2048, SHA-256, the name in the subject alternative names as Android's
/// host-name check requires) and names it as the guest's store does.
pub fn generate_trust_anchor(dir: &Path) -> Result<TrustAnchor, String> {
    let keystore = dir.join("release-host.p12");
    let pem = dir.join("release-host.pem");
    for stale in [&keystore, &pem] {
        if stale.exists() {
            std::fs::remove_file(stale)
                .map_err(|e| format!("removing {}: {e}", stale.display()))?;
        }
    }
    crate::run_status({
        let mut c = Command::new("keytool");
        c.args(["-genkeypair", "-keystore"])
            .arg(&keystore)
            .args(["-storetype", "PKCS12"])
            .args(["-storepass", KEYSTORE_PASSWORD])
            .args(["-keypass", KEYSTORE_PASSWORD])
            .args(["-alias", KEY_ALIAS])
            .args(["-keyalg", "RSA", "-keysize", "2048", "-validity", "30"])
            .args([
                "-dname",
                &format!("CN={RELEASE_HOST},O=HSE BLE Radar upgrade proof"),
            ])
            .args(["-ext", &format!("SAN=dns:{RELEASE_HOST}")]);
        c
    })?;
    crate::run_status({
        let mut c = Command::new("keytool");
        c.args(["-exportcert", "-rfc", "-keystore"])
            .arg(&keystore)
            .args(["-storetype", "PKCS12"])
            .args(["-storepass", KEYSTORE_PASSWORD])
            .args(["-alias", KEY_ALIAS])
            .arg("-file")
            .arg(&pem);
        c
    })?;
    let hash = Command::new("openssl")
        .args(["x509", "-noout", "-subject_hash_old", "-in"])
        .arg(&pem)
        .output()
        .map_err(|e| format!("running openssl: {e}"))?;
    if !hash.status.success() {
        return Err(format!(
            "openssl x509 -subject_hash_old failed: {}",
            String::from_utf8_lossy(&hash.stderr)
        ));
    }
    let android_name =
        android_cacert_name(&String::from_utf8_lossy(&hash.stdout)).ok_or_else(|| {
            format!(
                "openssl printed no subject hash: {:?}",
                String::from_utf8_lossy(&hash.stdout)
            )
        })?;
    Ok(TrustAnchor {
        keystore,
        pem,
        android_name,
    })
}

/// The file name Android's trust store gives a certificate, from OpenSSL's
/// `-subject_hash_old` output: eight hex digits, then `.0`.
pub fn android_cacert_name(openssl_output: &str) -> Option<String> {
    let hash = openssl_output.trim();
    (hash.len() == 8 && hash.chars().all(|c| c.is_ascii_hexdigit()))
        .then(|| format!("{}.0", hash.to_ascii_lowercase()))
}

/// The guest-side script (run as root) that makes the certificate a system
/// trust anchor on Android 14: the system store lives in the read-only
/// Conscrypt APEX, so a tmpfs copy of it plus the one new file is bind-mounted
/// over the store — in the root namespace, in each zygote's (apps forked from
/// now on inherit it) and in every process a zygote already forked. Its last
/// line lists the new file through the shadowed path, which the proof checks.
pub fn trust_anchor_injection_script(cert_name: &str) -> String {
    format!(
        "set -e\n\
         COPY={GUEST_CACERTS_COPY}\n\
         STORE={GUEST_CACERTS_DIR}\n\
         mkdir -p -m 700 $COPY\n\
         mount -t tmpfs tmpfs $COPY\n\
         cp $STORE/* $COPY/\n\
         cp {GUEST_PUSH_DIR}/{cert_name} $COPY/{cert_name}\n\
         chown root:root $COPY/*\n\
         chmod 644 $COPY/*\n\
         chcon u:object_r:system_security_cacerts_file:s0 $COPY/*\n\
         mount --bind $COPY $STORE\n\
         for Z in $(pidof zygote zygote64); do\n\
         \x20 nsenter --mount=/proc/$Z/ns/mnt -- mount --bind $COPY $STORE\n\
         \x20 for P in $(ps -o PID -P $Z | tail -n +2); do\n\
         \x20   nsenter --mount=/proc/$P/ns/mnt -- mount --bind $COPY $STORE || true\n\
         \x20 done\n\
         done\n\
         ls $STORE/{cert_name}\n"
    )
}

/// `CONNECT host:port HTTP/1.1` → `(host, port)`; anything else `None`.
pub fn connect_target(request_head: &str) -> Option<(String, u16)> {
    let first = request_head.lines().next()?;
    let mut parts = first.split_whitespace();
    if parts.next()? != "CONNECT" {
        return None;
    }
    let (host, port) = parts.next()?.rsplit_once(':')?;
    Some((host.to_string(), port.parse().ok()?))
}

/// What the proxy does with a tunnel request: only the release host's TLS
/// port is relayed (to the stand-in), everything else refused — the proof
/// must never become a path from the guest to the real internet.
pub fn tunnel_allowed(host: &str, port: u16) -> bool {
    host.eq_ignore_ascii_case(RELEASE_HOST) && port == 443
}

/// The proxy's log, summarised: how many tunnels reached the stand-in and
/// which hosts it refused. A guest's *global* proxy carries the platform's
/// own traffic too — its connectivity probes to `connectivitycheck.gstatic.com`
/// and `www.google.com`, Play's `generate_204` — so refusals are expected on
/// a runtime and reported, not failed; the app's own requests are held to the
/// stand-in's request log instead.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct TunnelSummary {
    /// Tunnels relayed to the stand-in (`github.com:443` only, by construction).
    pub relayed: usize,
    /// Requests refused, tunnel or plain.
    pub refused: usize,
    /// The distinct hosts refused, in the order first seen (`?` when a plain
    /// request carried no absolute URL to read one from).
    pub refused_hosts: Vec<String>,
    /// Lines that were neither: a stand-in that refused the upstream
    /// connection, an unreadable request.
    pub other: Vec<String>,
}

/// Reads the proxy's log lines (as [`serve_tunnel`] writes them).
pub fn tunnel_summary(tunnels: &[String]) -> TunnelSummary {
    let mut summary = TunnelSummary::default();
    for line in tunnels {
        if line.ends_with("-> relayed to the stand-in") {
            summary.relayed += 1;
        } else if let Some(host) = refused_host(line) {
            summary.refused += 1;
            if !summary.refused_hosts.contains(&host) {
                summary.refused_hosts.push(host);
            }
        } else {
            summary.other.push(line.clone());
        }
    }
    summary
}

/// The guest's default network as `dumpsys connectivity` reports it: the id
/// on the `Active default network:` line, and the transports and
/// capabilities of that network's `NetworkAgentInfo` line.
#[derive(Debug, PartialEq, Eq)]
pub struct ActiveNetwork {
    pub id: String,
    /// `WIFI`, `CELLULAR`, … (`|`-separated when several).
    pub transports: String,
    /// `NOT_METERED`, `INTERNET`, `VALIDATED`, … as the dump lists them.
    pub capabilities: Vec<String>,
}

impl ActiveNetwork {
    /// What `UpdateCheckService.detectNetworkType` reads as unmetered
    /// (`NET_CAPABILITY_NOT_METERED`), the state the core's download gate
    /// requires of a network the app may not use metered.
    pub fn unmetered(&self) -> bool {
        self.capabilities.iter().any(|c| c == "NOT_METERED")
    }
}

/// Reads [`ActiveNetwork`] from a `dumpsys connectivity` dump; `None` when
/// there is no default network (`none`) or its agent line is not found.
pub fn active_default_network(dump: &str) -> Option<ActiveNetwork> {
    let id = dump
        .lines()
        .find_map(|line| line.trim().strip_prefix("Active default network:"))?
        .trim();
    if id.is_empty() || id == "none" {
        return None;
    }
    let needle = format!("network{{{id}}}");
    let agent = dump
        .lines()
        .find(|line| line.contains("NetworkAgentInfo{") && line.contains(&needle))?;
    let (_, after_transports) = agent.split_once("Transports:")?;
    let (transports, after_capabilities) = after_transports.split_once("Capabilities:")?;
    let capabilities = after_capabilities
        .split_whitespace()
        .next()?
        .split('&')
        .map(str::to_string)
        .collect();
    Some(ActiveNetwork {
        id: id.to_string(),
        transports: transports.trim().to_string(),
        capabilities,
    })
}

/// The host a refusal line names: `CONNECT host:port -> refused`, or the
/// authority of the absolute URL a refused plain request carried.
fn refused_host(line: &str) -> Option<String> {
    if let Some(target) = line
        .strip_prefix("CONNECT ")
        .and_then(|rest| rest.strip_suffix(" -> refused"))
    {
        return Some(
            target
                .rsplit_once(':')
                .map_or(target, |(host, _)| host)
                .to_string(),
        );
    }
    let request_line = line.strip_prefix("refused a non-CONNECT request: ")?;
    let target = request_line.split_whitespace().nth(1).unwrap_or("");
    let authority = target
        .split_once("://")
        .map(|(_, rest)| rest.split('/').next().unwrap_or(""))
        .unwrap_or("");
    Some(if authority.is_empty() {
        "?".to_string()
    } else {
        authority.to_string()
    })
}

/// The stand-in release host and the proxy in front of it. Its logs are
/// read once, complete, by [`ReleaseHost::stop`]: the stand-in prints a
/// request's line after answering it, so a snapshot taken while it runs
/// could miss the last answer.
pub struct ReleaseHost {
    server: Child,
    /// Where the `HttpsServer` listens (loopback).
    pub https_port: u16,
    /// Where the `CONNECT` proxy listens (loopback; the guest reaches it as
    /// [`GUEST_HOST_ALIAS`]).
    pub proxy_port: u16,
    requests: Arc<Mutex<Vec<String>>>,
    tunnels: Arc<Mutex<Vec<String>>>,
    reader: Option<thread::JoinHandle<()>>,
}

/// What the stand-in must serve.
pub struct Release<'a> {
    /// The path of the app's release URL (`/…/releases/latest/download/release_manifest.txt`).
    pub latest_path: &'a str,
    /// The path the redirect names and the manifest is served at.
    pub manifest_path: &'a str,
    /// The manifest text to serve.
    pub manifest_file: &'a Path,
    /// The path the manifest's `url` names.
    pub apk_path: &'a str,
    /// The artifact to serve there.
    pub apk_file: &'a Path,
}

impl ReleaseHost {
    /// Compiles and starts the stand-in on `anchor`'s key, then the proxy.
    pub fn start(work: &Path, anchor: &TrustAnchor, release: &Release<'_>) -> Result<Self, String> {
        let source = work.join("ReleaseHost.java");
        let classes = work.join("release-host-classes");
        crate::recreate_dirs(&[&classes])?;
        std::fs::write(&source, RELEASE_HOST_JAVA_SOURCE)
            .map_err(|e| format!("writing {}: {e}", source.display()))?;
        crate::run_status({
            let mut c = Command::new("javac");
            c.args(["-encoding", "UTF-8", "-d"])
                .arg(&classes)
                .arg(&source);
            c
        })?;
        let mut command = Command::new("java");
        command
            .arg("-cp")
            .arg(&classes)
            .arg("ReleaseHost")
            .arg(&anchor.keystore)
            .arg(KEYSTORE_PASSWORD)
            .arg(RELEASE_HOST)
            .arg(release.latest_path)
            .arg(release.manifest_path)
            .arg(release.manifest_file)
            .arg(release.apk_path)
            .arg(release.apk_file)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::inherit());
        let mut server = command
            .spawn()
            .map_err(|e| format!("failed to spawn the stand-in release host: {e}"))?;
        let stdout = server
            .stdout
            .take()
            .ok_or("the stand-in's stdout was not captured")?;
        let requests: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
        let (port_tx, port_rx) = mpsc::channel();
        let sink = Arc::clone(&requests);
        let reader = thread::spawn(move || {
            let mut port_sent = false;
            for line in BufReader::new(stdout).lines().map_while(Result::ok) {
                if let Some(port) = line.strip_prefix("port=") {
                    if !port_sent {
                        let _ = port_tx.send(port.parse::<u16>().ok());
                        port_sent = true;
                    }
                } else if let Ok(mut log) = sink.lock() {
                    log.push(line);
                }
            }
        });
        let https_port = match port_rx.recv_timeout(SERVER_STARTUP_TIMEOUT) {
            Ok(Some(port)) => port,
            Ok(None) => {
                let _ = server.kill();
                return Err("the stand-in printed an unparsable port line".to_string());
            }
            Err(_) => {
                let _ = server.kill();
                return Err(format!(
                    "the stand-in release host did not report its port within {}s",
                    SERVER_STARTUP_TIMEOUT.as_secs()
                ));
            }
        };
        let tunnels: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
        let proxy_port = match spawn_connect_proxy(https_port, Arc::clone(&tunnels)) {
            Ok(port) => port,
            Err(error) => {
                let _ = server.kill();
                return Err(error);
            }
        };
        Ok(Self {
            server,
            https_port,
            proxy_port,
            requests,
            tunnels,
            reader: Some(reader),
        })
    }

    /// Stops the stand-in (closing its stdin, then insisting) and returns
    /// its complete logs: the requests it answered, in order (`request GET
    /// /path -> status`), and the tunnels the proxy was asked for. The
    /// stand-in's output is read to its end first, so the last answer's line
    /// is there.
    pub fn stop(mut self) -> (Vec<String>, Vec<String>) {
        drop(self.server.stdin.take());
        let deadline = Instant::now() + Duration::from_secs(10);
        while Instant::now() < deadline && !matches!(self.server.try_wait(), Ok(Some(_))) {
            thread::sleep(Duration::from_millis(100));
        }
        if !matches!(self.server.try_wait(), Ok(Some(_))) {
            let _ = self.server.kill();
            let _ = self.server.wait();
        }
        if let Some(reader) = self.reader.take() {
            let _ = reader.join();
        }
        (
            self.requests
                .lock()
                .map(|log| log.clone())
                .unwrap_or_default(),
            self.tunnels
                .lock()
                .map(|log| log.clone())
                .unwrap_or_default(),
        )
    }
}

/// The `url` field of a release manifest text (the first `=` splits, both
/// sides trimmed, as the core reads it).
pub fn manifest_url_field(text: &str) -> Option<String> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.starts_with('#'))
        .filter_map(|line| line.split_once('='))
        .find(|(key, _)| key.trim() == "url")
        .map(|(_, value)| value.trim().to_string())
}

/// Starts the `CONNECT` proxy on an ephemeral loopback port; every tunnel
/// request is logged, and only [`tunnel_allowed`] ones are relayed — to the
/// stand-in at `https_port`, whatever host the request named.
fn spawn_connect_proxy(https_port: u16, tunnels: Arc<Mutex<Vec<String>>>) -> Result<u16, String> {
    let listener =
        TcpListener::bind("127.0.0.1:0").map_err(|e| format!("binding the CONNECT proxy: {e}"))?;
    let port = listener
        .local_addr()
        .map_err(|e| format!("reading the proxy's address: {e}"))?
        .port();
    thread::spawn(move || {
        for client in listener.incoming().map_while(Result::ok) {
            let tunnels = Arc::clone(&tunnels);
            thread::spawn(move || serve_tunnel(client, https_port, &tunnels));
        }
    });
    Ok(port)
}

/// Reads one request head (through the blank line) from `client`.
fn read_request_head(client: &mut TcpStream) -> Result<String, String> {
    let _ = client.set_read_timeout(Some(Duration::from_secs(10)));
    let mut head = Vec::new();
    let mut byte = [0u8; 1];
    while !head.ends_with(b"\r\n\r\n") && head.len() < 8192 {
        match client.read(&mut byte) {
            Ok(1) => head.push(byte[0]),
            Ok(_) => break,
            Err(e) => return Err(format!("reading the tunnel request: {e}")),
        }
    }
    Ok(String::from_utf8_lossy(&head).into_owned())
}

fn serve_tunnel(mut client: TcpStream, https_port: u16, tunnels: &Mutex<Vec<String>>) {
    let log = |line: String| {
        if let Ok(mut tunnels) = tunnels.lock() {
            tunnels.push(line);
        }
    };
    let head = match read_request_head(&mut client) {
        Ok(head) => head,
        Err(error) => {
            log(format!("unreadable request: {error}"));
            return;
        }
    };
    let Some((host, port)) = connect_target(&head) else {
        log(format!(
            "refused a non-CONNECT request: {}",
            head.lines().next().unwrap_or_default()
        ));
        let _ = client.write_all(b"HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n");
        return;
    };
    if !tunnel_allowed(&host, port) {
        log(format!("CONNECT {host}:{port} -> refused"));
        let _ = client.write_all(b"HTTP/1.1 403 Forbidden\r\nConnection: close\r\n\r\n");
        return;
    }
    let upstream = match TcpStream::connect(("127.0.0.1", https_port)) {
        Ok(upstream) => upstream,
        Err(error) => {
            log(format!(
                "CONNECT {host}:{port} -> the stand-in refused: {error}"
            ));
            let _ = client.write_all(b"HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\n\r\n");
            return;
        }
    };
    if client
        .write_all(b"HTTP/1.1 200 Connection established\r\n\r\n")
        .is_err()
    {
        return;
    }
    log(format!("CONNECT {host}:{port} -> relayed to the stand-in"));
    let _ = client.set_read_timeout(None);
    relay(client, upstream);
}

/// Copies bytes both ways until either side closes.
fn relay(client: TcpStream, upstream: TcpStream) {
    let (Ok(mut client_reader), Ok(mut upstream_writer)) =
        (client.try_clone(), upstream.try_clone())
    else {
        return;
    };
    let forward = thread::spawn(move || {
        let _ = std::io::copy(&mut client_reader, &mut upstream_writer);
        let _ = upstream_writer.shutdown(Shutdown::Write);
    });
    let (mut upstream_reader, mut client_writer) = (upstream, client);
    let _ = std::io::copy(&mut upstream_reader, &mut client_writer);
    let _ = client_writer.shutdown(Shutdown::Write);
    let _ = forward.join();
}

/// `https://host/path` → `/path` when the host is [`RELEASE_HOST`].
pub fn release_url_path(url: &str) -> Option<&str> {
    let rest = url.strip_prefix("https://")?;
    let slash = rest.find('/')?;
    let (host, path) = rest.split_at(slash);
    (host.eq_ignore_ascii_case(RELEASE_HOST) && path.len() > 1).then_some(path)
}

/// How far the app's own log shows the upgrade got, from
/// `UpdateCheckService`'s lines: the download's id once enqueued, whether the
/// artifact verified, whether it was handed to the installer, and the first
/// line that ends the pathway short of that.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct UpgradeProgress {
    pub download_id: Option<u64>,
    pub verified: bool,
    pub handed_off: bool,
    pub failure: Option<String>,
}

/// Reads the pathway's milestones out of `logcat -s UpdateCheckService:*`.
pub fn upgrade_progress(logcat: &str) -> UpgradeProgress {
    let mut progress = UpgradeProgress::default();
    for line in logcat.lines() {
        let Some(message) = line.split("UpdateCheckService: ").nth(1) else {
            continue;
        };
        if let Some(id) = message.strip_prefix("Enqueued download with ID ") {
            progress.download_id = id.trim().parse().ok();
        } else if message.starts_with("Artifact verification passed") {
            progress.verified = true;
        } else if message.starts_with("Handed APK to system installer") {
            progress.handed_off = true;
        } else if progress.failure.is_none()
            && (message.starts_with("Download not ready")
                || message.starts_with("Download failed")
                || message.starts_with("Artifact verification failed")
                || message.starts_with("Failed to start download")
                || message.starts_with("Failed to install APK")
                || message.starts_with("DownloadManager has no URI")
                || message.starts_with("No safe update available")
                || message.starts_with("Could not load a release manifest")
                || message.contains("vanished from DownloadManager"))
        {
            progress.failure = Some(message.trim().to_string());
        }
    }
    progress
}

/// The `versionCode` `dumpsys package <pkg>` prints (`versionCode=2 minSdk=26 …`).
pub fn installed_version_code(dumpsys_package: &str) -> Option<u32> {
    dumpsys_package
        .split_whitespace()
        .find_map(|token| token.strip_prefix("versionCode=")?.parse().ok())
}

/// The centre of the first node in a `uiautomator dump` whose `text` is one
/// of `texts` (in that order of preference), from its `bounds="[x1,y1][x2,y2]"`.
pub fn ui_button_centre(ui_xml: &str, texts: &[&str]) -> Option<(u32, u32, String)> {
    for wanted in texts {
        let needle = format!("text=\"{wanted}\"");
        for node in ui_xml.split("<node ").skip(1) {
            if !node.contains(&needle) {
                continue;
            }
            let bounds = node.split("bounds=\"").nth(1)?.split('"').next()?;
            let numbers: Vec<u32> = bounds
                .split(|c: char| !c.is_ascii_digit())
                .filter(|digits| !digits.is_empty())
                .filter_map(|digits| digits.parse().ok())
                .collect();
            if let [x1, y1, x2, y2] = numbers[..] {
                return Some(((x1 + x2) / 2, (y1 + y2) / 2, (*wanted).to_string()));
            }
        }
    }
    None
}

/// The window a `dumpsys window displays` dump reports as focused
/// (`mCurrentFocus=Window{… pkg/activity}`; since Android 10 the `windows`
/// dump no longer carries it).
pub fn focused_window(dumpsys_window: &str) -> Option<String> {
    dumpsys_window
        .lines()
        .find_map(|line| line.split("mCurrentFocus=").nth(1))
        .map(|rest| rest.trim().to_string())
}

/// The activity `dumpsys activity activities` reports as resumed
/// (`topResumedActivity=ActivityRecord{… u0 pkg/activity t12}`): its
/// `pkg/activity`.
pub fn resumed_activity(dumpsys_activity: &str) -> Option<String> {
    dumpsys_activity
        .lines()
        .filter(|line| line.contains("ResumedActivity"))
        .find_map(|line| line.split("ActivityRecord{").nth(1))
        .and_then(|record| record.split('}').next())
        .and_then(|record| record.split_whitespace().nth(2))
        .map(str::to_string)
}

/// The host side proven on the host, before an emulator is involved: the
/// stand-in started on a fresh trust anchor, then `curl` — trusting only
/// that anchor, tunnelling through the proxy — fetching the app's release
/// URL (`release_manifest_url`, as the Java source declares it; its redirect
/// followed to the manifest, byte-identical), the artifact at the URL that
/// manifest names (byte-identical), and being refused a tunnel to another
/// host. Returns a one-line summary; run by `verify-api-live` so the `gates`
/// job covers it.
pub fn self_check(
    work: &Path,
    release_manifest_url: &str,
    manifest_text: &str,
    artifact: &Path,
) -> Result<String, String> {
    crate::recreate_dirs(&[work])?;
    let anchor = generate_trust_anchor(work)?;
    let manifest_file = work.join("release_manifest.txt");
    std::fs::write(&manifest_file, manifest_text)
        .map_err(|e| format!("writing {}: {e}", manifest_file.display()))?;
    let latest_path = release_url_path(release_manifest_url)
        .ok_or_else(|| {
            format!("the release URL `{release_manifest_url}` is not on https://{RELEASE_HOST}/")
        })?
        .to_string();
    let apk_url = manifest_url_field(manifest_text)
        .ok_or_else(|| format!("the manifest names no url:\n{manifest_text}"))?;
    let apk_path = release_url_path(&apk_url)
        .ok_or_else(|| format!("the manifest's url `{apk_url}` is not on https://{RELEASE_HOST}/"))?
        .to_string();
    let manifest_path = format!(
        "{}/release_manifest.txt",
        apk_path.rsplit_once('/').map_or("", |(dir, _)| dir)
    );
    let host = ReleaseHost::start(
        work,
        &anchor,
        &Release {
            latest_path: &latest_path,
            manifest_path: &manifest_path,
            manifest_file: &manifest_file,
            apk_path: &apk_path,
            apk_file: artifact,
        },
    )?;
    let (https_port, proxy_port) = (host.https_port, host.proxy_port);
    let fetched = (|| -> Result<usize, String> {
        let proxy = format!("http://127.0.0.1:{proxy_port}");
        let curl = |url: &str, out: &Path| -> Result<(String, String), String> {
            let output = Command::new("curl")
                .args(["-sS", "-L", "--proxy", &proxy, "--cacert"])
                .arg(&anchor.pem)
                .args(["-o"])
                .arg(out)
                .args(["-w", "%{http_code} %{url_effective}", url])
                .output()
                .map_err(|e| format!("running curl: {e}"))?;
            let written = String::from_utf8_lossy(&output.stdout).into_owned();
            let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
            if !output.status.success() {
                return Err(format!("curl {url} failed ({}): {stderr}", output.status));
            }
            Ok((written, stderr))
        };
        // The release URL: redirected to the manifest, whose text comes back
        // as served — over TLS the stand-in's anchor alone vouches for.
        let manifest_out = work.join("fetched_manifest.txt");
        let (written, _) = curl(release_manifest_url, &manifest_out)?;
        let manifest_url = format!("https://{RELEASE_HOST}{manifest_path}");
        if written != format!("200 {manifest_url}") {
            return Err(format!(
                "the release URL did not resolve to `200 {manifest_url}` through the proxy: {written}"
            ));
        }
        let fetched = std::fs::read_to_string(&manifest_out)
            .map_err(|e| format!("reading {}: {e}", manifest_out.display()))?;
        if fetched != manifest_text {
            return Err(format!(
                "the fetched manifest differs from the served text:\n{fetched}\n--- served ---\n{manifest_text}"
            ));
        }
        let artifact_out = work.join("fetched_artifact.bin");
        let (written, _) = curl(&apk_url, &artifact_out)?;
        if written != format!("200 {apk_url}") {
            return Err(format!(
                "the artifact URL did not answer 200 through the proxy: {written}"
            ));
        }
        let expected =
            std::fs::read(artifact).map_err(|e| format!("reading {}: {e}", artifact.display()))?;
        let fetched = std::fs::read(&artifact_out)
            .map_err(|e| format!("reading {}: {e}", artifact_out.display()))?;
        if fetched != expected {
            return Err(format!(
                "the fetched artifact differs from the served file ({} vs {} bytes)",
                fetched.len(),
                expected.len()
            ));
        }
        // Any other host is refused at the tunnel: the proxy is a path to
        // the stand-in, never to the internet.
        let refused = Command::new("curl")
            .args(["-sS", "--proxy", &proxy, "--cacert"])
            .arg(&anchor.pem)
            .args(["-o", "/dev/null", "https://example.com/"])
            .output()
            .map_err(|e| format!("running curl: {e}"))?;
        if refused.status.success() {
            return Err("the proxy tunnelled a request to example.com".to_string());
        }
        Ok(expected.len())
    })();
    // The logs are complete only once the stand-in has been stopped.
    let (requests, tunnels) = host.stop();
    let artifact_len = fetched?;
    if !tunnels
        .iter()
        .any(|line| line == "CONNECT example.com:443 -> refused")
    {
        return Err(format!(
            "the proxy did not log the refused tunnel: {}",
            tunnels.join(" | ")
        ));
    }
    let expected_requests = [
        format!("request GET {latest_path} -> 302"),
        format!("request GET {manifest_path} -> 200"),
        format!("request GET {apk_path} -> 200"),
    ];
    if requests != expected_requests {
        return Err(format!(
            "the stand-in's requests were not the three expected: {}",
            requests.join(" | ")
        ));
    }
    Ok(format!(
        "stand-in {RELEASE_HOST} on 127.0.0.1:{https_port} behind the CONNECT proxy on 127.0.0.1:{proxy_port}: the release URL {release_manifest_url} redirected to the manifest ({} bytes, byte-identical), the artifact it names fetched from {apk_url} ({artifact_len} bytes, byte-identical), a tunnel to example.com refused; trust anchor {}",
        manifest_text.len(),
        anchor.android_name
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tunnel_requests_are_parsed_and_only_the_release_host_is_relayed() {
        assert_eq!(
            connect_target("CONNECT github.com:443 HTTP/1.1\r\nHost: github.com:443\r\n\r\n"),
            Some(("github.com".to_string(), 443))
        );
        assert_eq!(
            connect_target("CONNECT [::1]:8443 HTTP/1.1\r\n\r\n"),
            Some(("[::1]".to_string(), 8443))
        );
        assert_eq!(connect_target("GET / HTTP/1.1\r\n\r\n"), None);
        assert_eq!(connect_target("CONNECT github.com HTTP/1.1\r\n\r\n"), None);
        assert_eq!(connect_target(""), None);
        assert!(tunnel_allowed("github.com", 443));
        assert!(tunnel_allowed("GitHub.com", 443));
        assert!(!tunnel_allowed("github.com", 80));
        assert!(!tunnel_allowed("api.github.com", 443));
        assert!(!tunnel_allowed("example.com", 443));
    }

    #[test]
    fn the_proxy_log_is_summarised_with_the_platforms_refused_hosts() {
        // The lines CI's first end-to-end run logged: the app's two tunnels
        // and the API 34 guest's own probes through the global proxy.
        let log: Vec<String> = [
            "CONNECT github.com:443 -> relayed to the stand-in",
            "CONNECT github.com:443 -> relayed to the stand-in",
            "refused a non-CONNECT request: GET http://connectivitycheck.gstatic.com/generate_204 HTTP/1.1",
            "CONNECT www.google.com:443 -> refused",
            "refused a non-CONNECT request: GET http://play.googleapis.com/generate_204 HTTP/1.1",
            "CONNECT infinitedata-pa.googleapis.com:443 -> refused",
            "CONNECT www.google.com:443 -> refused",
            "refused a non-CONNECT request: GET http://connectivitycheck.gstatic.com/generate_204 HTTP/1.1",
        ]
        .iter()
        .map(|line| line.to_string())
        .collect();
        let summary = tunnel_summary(&log);
        assert_eq!(summary.relayed, 2);
        assert_eq!(summary.refused, 6);
        assert_eq!(
            summary.refused_hosts,
            [
                "connectivitycheck.gstatic.com",
                "www.google.com",
                "play.googleapis.com",
                "infinitedata-pa.googleapis.com"
            ]
        );
        assert!(summary.other.is_empty());

        // What the summary does not absorb: the stand-in turning a tunnel
        // away, an unreadable request, and a plain request without a host.
        let odd: Vec<String> = [
            "CONNECT github.com:443 -> the stand-in refused: Connection refused (os error 111)",
            "unreadable request: early end of stream",
            "refused a non-CONNECT request: GET /generate_204 HTTP/1.1",
        ]
        .iter()
        .map(|line| line.to_string())
        .collect();
        let summary = tunnel_summary(&odd);
        assert_eq!(summary.relayed, 0);
        assert_eq!(summary.refused, 1);
        assert_eq!(summary.refused_hosts, ["?"]);
        assert_eq!(summary.other, odd[..2]);
        assert_eq!(tunnel_summary(&[]), TunnelSummary::default());
    }

    #[test]
    fn the_default_network_is_read_from_the_connectivity_dump() {
        // As ConnectivityService dumps it: the id, then every agent's line
        // under "Current Networks:" (NetworkAgentInfo.toString, the
        // capabilities in NetworkCapabilities.toString's form).
        let dump = "NetworkProviders for: WifiNetworkFactory TelephonyNetworkProvider\n\
                    \n\
                    Active default network: 101\n\
                    \n\
                    Current Networks:\n\
                    \x20 NetworkAgentInfo{network{100}  handle{429496729601}  ni{[type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: epc.tmobile.com]} Score(...) everValidated{true} nc{[ Transports: CELLULAR Capabilities: MMS&SUPL&DUN&FOTA&IMS&CBS&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=51200Kbps LinkDnBandwidth>=102400Kbps Specifier: <TelephonyNetworkSpecifier [mSubId = 1]> SubscriptionIds: {1} UnderlyingNetworks: Null]} }\n\
                    \x20   Requests: REQUEST:3 LISTEN:5 BACKGROUND_REQUEST:0 total:8\n\
                    \x20 NetworkAgentInfo{network{101}  handle{433791696901}  ni{[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: \"AndroidWifi\"]} Score(...) everValidated{true} nc{[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps TransportInfo: <SSID: \"AndroidWifi\", BSSID: 00:13:10:85:fe:01> SSID: \"AndroidWifi\" UnderlyingNetworks: Null]} }\n";
        let network = active_default_network(dump).expect("the Wi-Fi network");
        assert_eq!(network.id, "101");
        assert_eq!(network.transports, "WIFI");
        assert!(network.unmetered());
        assert_eq!(network.capabilities[0], "NOT_METERED");
        assert_eq!(network.capabilities.last().unwrap(), "NOT_VCN_MANAGED");

        // Cellular as the default: found, and metered.
        let cellular = dump.replace("Active default network: 101", "Active default network: 100");
        let network = active_default_network(&cellular).expect("the cellular network");
        assert_eq!(
            (network.id.as_str(), network.transports.as_str()),
            ("100", "CELLULAR")
        );
        assert!(!network.unmetered());

        // No default network, an unknown id, no dump at all.
        assert_eq!(
            active_default_network(&dump.replace(
                "Active default network: 101",
                "Active default network: none"
            )),
            None
        );
        assert_eq!(
            active_default_network(
                &dump.replace("Active default network: 101", "Active default network: 7")
            ),
            None
        );
        assert_eq!(active_default_network(""), None);
    }

    #[test]
    fn the_android_store_name_and_the_injection_script_follow_the_platform() {
        assert_eq!(
            android_cacert_name("A1B2C3D4\n"),
            Some("a1b2c3d4.0".to_string())
        );
        assert_eq!(android_cacert_name("nonsense"), None);
        assert_eq!(android_cacert_name(""), None);
        let script = trust_anchor_injection_script("a1b2c3d4.0");
        assert!(script.starts_with("set -e\n"));
        assert!(script.contains("COPY=/data/local/tmp/cacerts-copy\n"));
        assert!(script.contains("STORE=/apex/com.android.conscrypt/cacerts\n"));
        assert!(script.contains("mount -t tmpfs tmpfs $COPY\n"));
        assert!(script.contains("cp /data/local/tmp/a1b2c3d4.0 $COPY/a1b2c3d4.0"));
        assert!(script.contains("chcon u:object_r:system_security_cacerts_file:s0"));
        assert!(script.contains("mount --bind $COPY $STORE"));
        assert!(script.contains("nsenter --mount=/proc/$Z/ns/mnt"));
        assert!(script.contains("pidof zygote zygote64"));
        assert!(script.ends_with("ls $STORE/a1b2c3d4.0\n"));
        assert!(RELEASE_HOST_JAVA_SOURCE.contains("HttpsServer.create"));
        assert!(RELEASE_HOST_JAVA_SOURCE.contains("\"port=\""));
        assert!(RELEASE_HOST_JAVA_SOURCE.contains("Location"));
    }

    #[test]
    fn the_release_url_path_is_the_part_after_the_release_host() {
        assert_eq!(
            release_url_path(
                "https://github.com/EmmmmDeee/HSE-BLE-API-/releases/latest/download/release_manifest.txt"
            ),
            Some("/EmmmmDeee/HSE-BLE-API-/releases/latest/download/release_manifest.txt")
        );
        assert_eq!(release_url_path("https://example.com/x"), None);
        assert_eq!(release_url_path("http://github.com/x"), None);
        assert_eq!(release_url_path("https://github.com"), None);
        assert_eq!(
            manifest_url_field(
                "# a comment\nversion_code = 2\nurl = https://github.com/x/y.apk \nnotes = url = not this\n"
            )
            .as_deref(),
            Some("https://github.com/x/y.apk")
        );
        assert_eq!(manifest_url_field("version_code = 2\n"), None);
    }

    #[test]
    fn the_pathway_milestones_are_read_from_the_service_log() {
        let log = "09-14 10:00:01.000  4000  4020 I UpdateCheckService: Remote manifest https://github.com/x: HTTP 200, 300 bytes -> using the remote manifest\n\
                   09-14 10:00:01.100  4000  4020 D UpdateCheckService: Update decision: 1 (available=1)\n\
                   09-14 10:00:01.200  4000  4020 D UpdateCheckService: Downloading update from: https://github.com/y.apk\n\
                   09-14 10:00:01.300  4000  4020 D UpdateCheckService: Enqueued download with ID 7\n\
                   09-14 10:00:03.000  4000  4000 D UpdateCheckService: Artifact verification passed\n\
                   09-14 10:00:03.100  4000  4000 D UpdateCheckService: Handed APK to system installer\n";
        assert_eq!(
            upgrade_progress(log),
            UpgradeProgress {
                download_id: Some(7),
                verified: true,
                handed_off: true,
                failure: None,
            }
        );
        let blocked = "I UpdateCheckService: Update decision: 1 (available=1)\nD UpdateCheckService: Download not ready (readiness=2); will retry later\n";
        assert_eq!(
            upgrade_progress(blocked).failure.as_deref(),
            Some("Download not ready (readiness=2); will retry later")
        );
        let hash = "D UpdateCheckService: Enqueued download with ID 9\nE UpdateCheckService: Artifact verification failed: SHA-256 differs from the manifest\n";
        let progress = upgrade_progress(hash);
        assert_eq!(progress.download_id, Some(9));
        assert!(!progress.verified);
        assert!(
            progress
                .failure
                .as_deref()
                .unwrap()
                .starts_with("Artifact verification failed")
        );
        assert_eq!(upgrade_progress(""), UpgradeProgress::default());
    }

    #[test]
    fn package_and_window_dumps_are_read() {
        assert_eq!(
            installed_version_code(
                "Packages:\n  Package [com.hse.bleradar] (1234):\n    versionCode=2 minSdk=26 targetSdk=34\n    versionName=1.0.1\n"
            ),
            Some(2)
        );
        assert_eq!(installed_version_code("Unable to find package"), None);
        let ui = r#"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><hierarchy rotation="0"><node index="0" text="" class="android.widget.FrameLayout" bounds="[0,0][1080,2400]"><node index="1" text="Cancel" class="android.widget.Button" bounds="[100,2000][400,2100]" /><node index="2" text="Update" class="android.widget.Button" bounds="[600,2000][980,2100]" /></node></hierarchy>"#;
        assert_eq!(
            ui_button_centre(ui, &["Install", "Update"]),
            Some((790, 2050, "Update".to_string()))
        );
        assert_eq!(ui_button_centre(ui, &["Install"]), None);
        assert_eq!(
            focused_window("  mCurrentFocus=Window{abc u0 com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}\n"),
            Some("Window{abc u0 com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}".to_string())
        );
        assert_eq!(focused_window("nothing"), None);
        let activities = "  Task id #12\n    topResumedActivity=ActivityRecord{6d0f8a2 u0 com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity t12}\n";
        assert_eq!(
            resumed_activity(activities).as_deref(),
            Some(
                "com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity"
            )
        );
        assert_eq!(
            resumed_activity(
                "  ResumedActivity: ActivityRecord{abc u0 com.hse.bleradar/.MainActivity t9}\n"
            )
            .as_deref(),
            Some("com.hse.bleradar/.MainActivity")
        );
        assert_eq!(resumed_activity("no such line"), None);
    }
}
